import {ConfirmCreatorInvoice} from "@/features/billing/components/confirm-creator-invoice";
import {FinanceSuiteShell} from '@/components/finance/suite/finance-suite-shell';import {createSupabaseServerClient} from '@/lib/supabase/server';import {planningDb} from '@/lib/supabase/governance-client';import {requireFinancePermission} from '@/lib/auth/permissions-server';import {CreatorInvoiceForm,type CreatorInvoiceChoice} from '@/features/billing/components/creator-invoice-form';
export const dynamic='force-dynamic';
export default async function CreatorInvoicesPage({searchParams}:{searchParams:Promise<{assignment?:string}>}){
 const db=await createSupabaseServerClient();const auth=await requireFinancePermission(db,'finance.read');if('error' in auth)return <FinanceSuiteShell title="Creator invoices"><p>{auth.error}</p></FinanceSuiteShell>;
 const [assignments,records,ios]=await Promise.all([db.from('campaign_influencers').select('id,currency,agreed_fee,influencer:influencers(display_name,legal_name,country_code),campaign:campaign_headers!campaign_influencers_campaign_header_id_fkey(name)').order('id').limit(1000),planningDb(db).from('creator_supplier_invoices').select('*').order('created_at',{ascending:false}).limit(1000),planningDb(db).from('vendor_ios').select('assignment_id,document_number').order('created_at',{ascending:false})]);
 if(assignments.error||records.error||ios.error)return <FinanceSuiteShell title="Creator invoices"><p>Invoice records are unavailable. Reload or check Finance access.</p></FinanceSuiteShell>;
 const choices:CreatorInvoiceChoice[]=(assignments.data??[]).map((r:any)=>{const creator=Array.isArray(r.influencer)?r.influencer[0]:r.influencer;const campaign=Array.isArray(r.campaign)?r.campaign[0]:r.campaign;const code=(creator?.country_code??'').toUpperCase();return {id:r.id,currency:r.currency,fee:Number(r.agreed_fee??0),creator:creator?.legal_name||creator?.display_name||'Creator',campaign:campaign?.name??'Campaign',country:({EGYPT:'EG','UNITED ARAB EMIRATES':'AE',UAE:'AE','SAUDI ARABIA':'SA'} as Record<string,string>)[code]||(code.length===2?code:''),io:ios.data?.find(i=>i.assignment_id===r.id)?.document_number??''};});
 const documents=await Promise.all((records.data??[]).map(async r=>({...r,url:r.storage_path?(await db.storage.from('creator-invoices').createSignedUrl(r.storage_path,600)).data?.signedUrl:null})));
 return <FinanceSuiteShell title="Creator invoices" description="Received and missing supplier invoices, including already-paid assignments"><CreatorInvoiceForm choices={choices} initial={(await searchParams).assignment??''}/><div className="mt-4 overflow-x-auto rounded-xl border bg-white p-4"><h2 className="font-semibold">Invoice register · latest 1,000 records</h2><table className="w-full text-left text-sm"><thead><tr>{['Creator / campaign','Invoice / status','Invoice date','Due','Currency','Before VAT','VAT','Total','Review','Attachment'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{documents.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.supplier_name}<p>{choices.find(a=>a.id===r.assignment_id)?.campaign}</p></td><td className="p-3">{r.invoice_number||r.status.replaceAll('_',' ')}<details><summary>Details</summary><p>{r.supplier_address||'Address not set'}</p><p>Tax registration: {r.tax_registration_number||'Not set'}</p><p>{r.description}</p><p>{r.notes}</p></details></td><td className="p-3">{r.invoice_date||'Not set'}</td><td className="p-3">{r.due_date||'Not set'}</td><td className="p-3">{r.currency}</td>{[r.subtotal,r.vat_amount,Number(r.subtotal)+Number(r.vat_amount)].map((n,i)=><td key={i} className="p-3 tabular-nums">{Number(n).toLocaleString('en-GB',{minimumFractionDigits:2})}</td>)}<td className="p-3">{r.confirmed?'Confirmed':r.status==='received'?<ConfirmCreatorInvoice id={r.id}/>:'Not received'}</td><td className="p-3">{r.url?<a href={r.url} target="_blank" rel="noreferrer" className="text-blue-600">Open document</a>:'No attachment'}</td></tr>)}</tbody></table>{!documents.length&&<p>No creator invoices recorded yet.</p>}</div></FinanceSuiteShell>;
}
