/**
 * Public bank metadata only; never learn routing from another creator's account.
 * UAE code/BIC directory: HSBC, List of Beneficiary Bank Codes, March 2022:
 * https://www.business.hsbc.ae/-/media/library/markets-selective/uae/pdf/list-of-beneficiary-bank-codes-for-autopay-services.pdf
 * Reviewed 2026-09-21. Excludes exchange houses, placeholder BICs and legacy
 * merged-bank entries whose current routing cannot be established from this list.
 * Egypt codes: https://docs.dlocal.com/docs/egypt-payouts-v3#bank-codes
 * Egypt BICs: https://tranglo.com/docs/tranglo-connect/service-specification/egypt/
 * Additional receiving instructions: https://www.afnci.org.eg/?page_id=22451 (published receiving instructions)
 * https://askaribank.com/gallery/List-of-Correspondent-Banks.pdf
 * Saudi codes/BICs: https://developer.anb.com.sa/apis/api/single-payment (Appendix B).
 * EG/SA reviewed 2026-09-22. Empty BIC means name-only recognition: do not guess
 * routing for legacy/merged banks or invent a branch-specific BIC from an IBAN.
 * A directory match is not confirmation of account ownership or bank acceptance.
 */
export const IBAN_BANKS: Readonly<Record<string, Readonly<Record<string, readonly [name: string, swift: string]>>>> = {
    EG: {
        '0002': ['Banque Misr', 'BMISEGCX'],
        '0003': ['National Bank of Egypt', 'NBEGEGCX'],
        '0004': ['Banque du Caire', 'BCAIEGCX'],
        '0005': ['Bank of Alexandria', 'ALEXEGCX'],
        '0007': ['Egyptian Arab Land Bank', 'ARLBEGCA'],
        '0008': ['Industrial Development Bank', 'DIBBEGCA'],
        '0009': ['Agricultural Bank of Egypt', 'BDACEGCA'],
        '0010': ['Commercial International Bank Egypt', 'CIBEEGCX'],
        '0013': ['Blom Bank Egypt (legacy code)', ''],
        '0014': ['Emirates NBD Egypt', 'EBILEGCX'],
        '0017': ['Suez Canal Bank', 'SUCAEGCX'],
        '0018': ['Al Ahli Bank of Kuwait - Egypt', 'ECBAEGCA'],
        '0019': ['Bank Audi Egypt (legacy code)', ''],
        '0020': ['Kuwait Finance House Egypt (formerly Ahli United Bank)', 'DEIBEGCX'],
        '0022': ['Al Baraka Bank Egypt', 'ABRKEGCA'],
        '0023': ['National Bank of Kuwait - Egypt', 'WABAEGCX'],
        '0025': ['HSBC Bank Egypt', 'EBBKEGCX'],
        '0027': ['Abu Dhabi Commercial Bank - Egypt', 'ADCBEGCX'],
        '0029': ['Egyptian Gulf Bank', 'EGGBEGCA'],
        '0030': ['Abu Dhabi Islamic Bank - Egypt', 'ABDIEGCA'],
        '0031': ['The United Bank', 'UBOEEGCX'],
        '0033': ['MIDBANK', 'MIDBEGCX'],
        '0034': ['Attijariwafa Bank Egypt', 'BCBIEGCX'],
        '0035': ['Societe Arabe Internationale de Banque', 'SBNKEGCX'],
        '0036': ['Credit Agricole Egypt', 'AGRIEGCX'],
        '0037': ['QNB Egypt', 'QNBAEGCX'],
        '0038': ['Housing and Development Bank', 'HDBKEGCA'],
        '0040': ['Bank ABC Egypt', 'EAABEGCX'],
        '0042': ['First Abu Dhabi Bank Egypt', 'NBADEGCA'],
        '0043': ['Citibank Egypt', 'CITIEGCX'],
        '0044': ['Arab Bank Egypt', 'ARABEGCX'],
        '0046': ['Mashreq Bank Egypt', 'MSHQEGCA'],
        '0048': ['National Bank of Greece Egypt (legacy code)', ''],
        '0056': ['Arab International Bank', 'ARIBEGCX'],
        '0057': ['Arab African International Bank', 'ARAIEGCX'],
        '0058': ['Arab Investment Bank', 'AINBEGCA'],
        '0059': ['Faisal Islamic Bank of Egypt', 'FIEGEGCX'],
        '0061': ['Export Development Bank of Egypt', 'EXDEEGCX'],
        '9003': ['Nasser Social Bank', 'NSOBEGC1'],
    },
    SA: {
        '01': ['Saudi Central Bank', 'SAMASARI'],
        '05': ['Alinma Bank', 'INMASARI'],
        '10': ['Saudi National Bank', 'NCBKSAJE'],
        '15': ['Bank Albilad', 'ALBISARI'],
        '20': ['Riyad Bank', 'RIBLSARI'],
        '30': ['Arab National Bank', 'ARNBSARI'],
        '36': ['D360 Bank', 'DBAKSARI'],
        '45': ['Saudi Awwal Bank', 'SABBSARI'],
        '55': ['Banque Saudi Fransi', 'BSFRSARI'],
        '60': ['Bank AlJazira', 'BJAZSAJE'],
        '65': ['Saudi Investment Bank', 'SIBCSARI'],
        '71': ['National Bank of Bahrain', 'NBOBSARI'],
        '72': ['Qatar National Bank', 'QNBASARI'],
        '73': ['First Abu Dhabi Bank', 'FABMSARI'],
        '75': ['National Bank of Kuwait', 'NBOKSAJE'],
        '76': ['Bank Muscat', 'BMUSSARI'],
        '78': ['STC Bank', 'STCJSARI'],
        '79': ['National Bank of Iraq', 'NBIQSARI'],
        '80': ['Al Rajhi Bank', 'RJHISARI'],
        '81': ['Deutsche Bank', 'DEUTSARI'],
        '82': ['National Bank of Pakistan', 'NBPASARI'],
        '84': ['T.C. Ziraat Bankasi', 'TCZBSARI'],
        '85': ['BNP Paribas', 'BNPASARI'],
        '86': ['JP Morgan Chase', 'CHASSARI'],
        '87': ['Industrial and Commercial Bank of China', 'ICBKSARI'],
        '88': ['MUFG Bank', 'BOTKSARI'],
        '89': ['Credit Suisse', 'CRESSARY'],
        '90': ['Gulf International Bank', 'GULFSARI'],
        '91': ['Standard Chartered Bank', 'SCBLSAR2'],
        '92': ['Sohar International Bank', 'BSHRSARI'],
        '93': ['Vision Bank', 'VIIOSARI'],
        '95': ['Emirates NBD', 'EBILSARI'],
    },
    AE: {
        '003': ['Abu Dhabi Commercial Bank', 'ADCBAEAA'],
        '004': ['Al Ahli Bank of Kuwait', 'ABKKAEAD'],
        '005': ['Rafidain Bank', 'RAFBAEAD'],
        '007': ['Arab African International Bank', 'ARAIAEAD'],
        '008': ['Al Masraf', 'ABINAEAA'],
        '009': ['Arab Bank', 'ARABAEAD'],
        '011': ['Bank of Baroda', 'BARBAEAD'],
        '012': ['Bank of Sharjah', 'SHARAEAS'],
        '014': ['Blom Bank France', 'BLOMAEAD'],
        '015': ['Banque Misr', 'BMISAEAA'],
        '016': ['Credit Agricole Corporate and Investment Bank', 'BSUIAEAD'],
        '018': ['BNP Paribas', 'BNPAAEAA'],
        '019': ['Barclays Bank', 'BARCAEAD'],
        '020': ['HSBC Bank Middle East', 'BBMEAEAD'],
        '021': ['Citibank NA', 'CITIAEAD'],
        '022': ['Commercial Bank International', 'CLBIAEAD'],
        '023': ['Commercial Bank of Dubai', 'CBDUAEAD'],
        '024': ['Dubai Islamic Bank', 'DUIBAEAD'],
        '025': ['El Nilein Bank', 'NILBAEAA'],
        '026': ['Emirates NBD Bank PJSC', 'EBILAEAD'],
        '028': ['Habib Bank Limited', 'HABBAEAD'],
        '029': ['Habib Bank AG Zurich', 'HBZUAEAD'],
        '030': ['Investbank', 'IBTFAEAS'],
        '031': ['Janata Bank', 'JANBAEAA'],
        '033': ['Mashreq Bank', 'BOMLAEAD'],
        // Also confirmed by https://www.emiratesislamic.ae/en/help-and-support/your-iban-and-swift
        '034': ['Emirates Islamic Bank PJSC', 'MEBLAEAD'],
        // Current name/BIC and code 035 corroborated by RBI's 2026 settlement instructions:
        // https://www.rbinternational.com/content/dam/rbi/ho/corporates/our-solutions/cash-management/RBI_Productsheet_CommercialPayments-SSI_MainCorrespondents_EN.pdf.coredownload.pdf
        '035': ['First Abu Dhabi Bank PJSC', 'NBADAEAA'],
        '036': ['National Bank of Bahrain', 'NBOBAEAA'],
        '038': ['National Bank of Fujairah', 'NBFUAEAF'],
        '039': ['National Bank of Oman', 'NBOMAEAD'],
        '040': ['National Bank of Ras Al-Khaimah (RAKBANK)', 'NRAKAEAK'],
        '041': ['Sharjah Islamic Bank', 'NBSHAEAS'],
        '042': ['National Bank of Umm Al Qaiwain', 'UMMQAEAD'],
        '043': ['Industrial and Commercial Bank of China', 'ICBKAEAA'],
        '044': ['Standard Chartered Bank', 'SCBLAEAD'],
        '046': ['United Arab Bank', 'UARBAEAA'],
        '047': ['United Bank Limited', 'UNILAEAD'],
        '049': ['Deutsche Bank', 'DEUTAEAA'],
        '050': ['Abu Dhabi Islamic Bank', 'ABDIAEAD'],
        '053': ['Al Hilal Bank', 'HLALAEAA'],
        '054': ['Doha Bank', 'DOHBAEAD'],
        '056': ['National Bank of Kuwait', 'NBOKAEAD'],
        '057': ['Ajman Bank', 'AJMNAEAJ'],
        // Existing verified mapping, newer than the HSBC directory:
        // https://convera.com/en-gb/resources/iban-codes/united-arab-emirates/ae560860000009192749396/
        // https://ibanapi.com/bank/43434/wio-bank-p.j.s.c.
        '086': ['Wio Bank PJSC', 'WIOBAEAD'],
        '092': ['Gulf International Bank', 'GULFAEAA'],
        '093': ['Intesa Sanpaolo', 'BCITAEAB'],
        // https://www.mbank.ae/ (routing 009710001 and BIC)
        '097': ['Al Maryah Community Bank', 'E097AEXX'],
        // https://business.ruyabank.ae/ (routing 413240101 and BIC)
        '132': ['Ruya Community Islamic Bank', 'E132AEXX'],
    },
};
