/**
 * Mock-seed / demo discovery profiles are permanently disabled in every runtime.
 * Keep in sync with lib/discovery/demo-data.ts
 */
export function isDemoDataEnabled(
  _env: NodeJS.ProcessEnv = process.env
): boolean {
  return false;
}

/** Username pattern generated by the (now-removed) discovery-worker mock-seed fallback. */
export const MOCK_SEED_USERNAME_RE = /^tw_[a-z0-9]+_[a-z]{2}_[0-9]{2}$/i;

export function isMockSeedUsername(username: string | null | undefined): boolean {
  if (!username) return false;
  return MOCK_SEED_USERNAME_RE.test(username);
}

/**
 * Any username prefix that could only originate from synthetic/demo/mock/seed
 * generators. Real creator handles never start with these tokens.
 */
export const SYNTHETIC_CREATOR_USERNAME_RE = /^(tw|demo|mock|seed|fake)_/i;

export function isSyntheticCreatorUsername(
  username: string | null | undefined
): boolean {
  if (!username) return false;
  return (
    SYNTHETIC_CREATOR_USERNAME_RE.test(username) || isMockSeedUsername(username)
  );
}
