"use client";
import type {OfferAction} from "./offer-actions";
import {Fragment,useState} from "react";
import {CreatorAvatarImage} from "@/components/creator/creator-avatar-image";
import {Button} from "@/components/ui/button";
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from "@/components/ui/dropdown-menu";
import {TravelUpliftCell} from "./travel-editor";
import {travelFields,type TravelUplifts} from "./travel";
import type {RateLine} from "./model";
import type {RatePair} from "./template-rows";
import {rateOffers,lineMoney} from "./offer-adapter";
import {useRateLanguage} from "./ui";
import {taxonomyLabel,rxText} from "./labels";
import {formatMoney,formatPct,grossProfitPct,markupPct,incomparableReason,agencyFeeSummary,periodicTotal,isMissing,type Money} from "./lib/pricing";
export function ServiceRateTable({lines,avatars,editable,selected,onSelect,onEdit,onAvatar,onTravel,onOfferAction,onRemove}:{lines:RateLine[];avatars:Record<string,string>;editable:boolean;selected:Set<string>;onTravel:(line:RateLine,values:TravelUplifts)=>Promise<void>;onSelect:(ids:string[])=>void;onEdit:(line:Partial<RateLine>)=>void;onAvatar:(line:RateLine)=>void;onOfferAction:(line:RateLine,mode:OfferAction)=>void;onRemove:(ids:string[],name:string)=>void;}){
 const {lang,t}=useRateLanguage();const ar=lang==="ar";const tr=(k:Parameters<typeof rxText>[1])=>rxText(lang,k);const [expanded,setExpanded]=useState<Set<string>>(new Set());const [view,setView]=useState("all");
 const offers=rateOffers(lines,avatars,lang);const visible=offers.filter(({offer:o})=>view==="all"||(view==="extras"?!!(o.usageRights||o.boosting||o.eventAttendance):isMissing(o.creatorCost)||isMissing(o.clientPrice)));
 const toggle=(id:string)=>setExpanded(old=>{const n=new Set(old);if(n.has(id))n.delete(id);else n.add(id);return n;});
 const money=(m:Money)=><span className={`rx-money ${m.amount===0?"is-zero":""}`}>{isMissing(m)?<span className="rx-miss">{tr("notSet")}</span>:<><b dir="ltr">{formatMoney(m,lang)}</b><u>{m.currency??tr("notSet")}</u></>}</span>;
 const ids=visible.flatMap(({row})=>row.ids);const allSelected=!!ids.length&&ids.every(id=>selected.has(id));
 return <><div className="rx-offer-filter"><div className="rx-tabs" role="group" aria-label={ar?"عرض عروض الصفحة الحالية":"Offers on this page"}>{[["all",ar?"كل العروض":"All offers"],["extras",ar?"بخدمات اختيارية":"With optional services"],["missing",ar?"أسعار غير محددة":"Missing prices"]].map(([v,label])=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{label}</button>)}</div><small>{ar?"تصفية العروض في الصفحة الحالية":"Filters offers on the current page"}</small></div>
 <div className="rx-tbl"><div className="rx-scroll" tabIndex={0} role="region" aria-label={ar?"جدول الأسعار":"Pricing table"}><table className="rx-pricing-table"><colgroup>{[38,260,80,110,115,80,85,105,180,80].map((width,i)=><col key={i} style={{width}}/>)}</colgroup><thead><tr className="rx-privacy"><th colSpan={3}/><th className="priv">{ar?"داخلي · خاص":"Internal · private"}</th><th className="pub">{ar?"للعميل":"Client-facing"}</th><th className="priv" colSpan={2}>{ar?"داخلي · خاص":"Internal · private"}</th><th colSpan={3}/></tr><tr><th><input type="checkbox" disabled={!editable||!ids.length} checked={allSelected} ref={el=>{if(el)el.indeterminate=!allSelected&&ids.some(id=>selected.has(id));}} aria-label={ar?"تحديد كل عروض هذه الصفحة":"Select all offers on this page"} onChange={()=>onSelect(ids)}/></th>{[t("creator"),t("platform"),t("creator_cost"),t("client_price"),"GP %",ar?"الهامش %":"Markup %",t("agencyFee"),ar?"خدمات اختيارية":"Optional services",t("action")].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>
 {visible.map(({offer:o,row})=>{
  const open=expanded.has(o.id);const gp=grossProfitPct(o.creatorCost,o.clientPrice),markup=markupPct(o.creatorCost,o.clientPrice);const reason=incomparableReason(o.creatorCost,o.clientPrice)??"A currency is missing";
  const reasonAr:Record<string,string>={"A price is missing":"أحد الأسعار غير محدد","Currencies differ":"العملات مختلفة","Client price is zero":"سعر العميل صفر","Creator cost is zero":"تكلفة المبدع صفر","A currency is missing":"إحدى العملات غير محددة"};
  const pct=(n:number|null)=><span className={n===null?"rx-na":""} title={n===null?(ar?reasonAr[reason]:reason):undefined} tabIndex={n===null?0:undefined}>{formatPct(n)}</span>;
  const edit=(rate:RateLine|undefined,type:"creator_cost"|"client_price",deliverable:string)=>onEdit(rate??{...row.line,id:undefined,deliverable,price_type:type,amount:undefined,agency_fee_percent:null,notes:"",event_days:1,period_months:["usage_right","boosting"].includes(deliverable)?1:0});
  const price=(rate:RateLine|undefined,type:"creator_cost"|"client_price",deliverable:string,enabled=true)=><div className="rx-price-cell">{money(lineMoney(rate))}{editable&&enabled&&<button className="rx-link" aria-label={`${t(rate?"edit":"add")} ${t(type)} · ${o.creatorName} · ${taxonomyLabel(deliverable,lang)}`} onClick={()=>edit(rate,type,deliverable)}>{rate?t("edit"):(ar?"إضافة":"Add")}</button>}</div>;
  const extras=[{pair:row.usage,data:o.usageRights,key:"usage_right",label:ar?"حقوق الاستخدام":"Usage rights",cls:"ur"},{pair:row.boost,data:o.boosting,key:"boosting",label:ar?"الترويج":"Boosting",cls:"bo"},{pair:row.event,data:o.eventAttendance,key:"event_attendance",label:ar?"حضور الفعالية":"Event attendance",cls:"ev"}];
  const fee=agencyFeeSummary([o.agencyFeePct,o.usageRights?.agencyFeePct??null,o.boosting?.agencyFeePct??null,o.eventAttendance?.agencyFeePct??null]);
  const quantity=(pair:RatePair,event:boolean)=>{const a=pair.cost?(event?pair.cost.event_days??1:pair.cost.period_months??null):null,b=pair.client?(event?pair.client.event_days??1:pair.client.period_months??null):null;const unit=event?(ar?"يوم":"d"):(ar?"شهر":"m");return a!=null&&b!=null&&a!==b?`${t("creator_cost")}: ${a}${unit} / ${t("client_price")}: ${b}${unit}`:`${b??a??tr("notSet")}${b??a?unit:""}`;};
  return <Fragment key={o.id}><tr className={row.ids.every(id=>selected.has(id))?"is-sel":""}><td><input type="checkbox" disabled={!editable} checked={row.ids.every(id=>selected.has(id))} aria-label={`${t("select")} ${o.creatorName} ${o.packageName??o.deliverableType}`} onChange={()=>onSelect(row.ids)}/></td>
  <td><div className="rx-offer"><CreatorAvatarImage avatarUrl={o.avatarUrl} size="sm" className="!border-0"/><div className="rx-offer__t"><button className="rx-link rx-creator-link" title={o.creatorName} onClick={()=>onOfferAction(row.line,"details")}><bdi dir="auto">{o.creatorName}</bdi></button><u>{o.packageName??taxonomyLabel(o.deliverableType,lang)}</u><span className="rx-comp" title={o.composition??undefined}>{o.composition}</span><span className="rx-p">{o.pricingLineIds.length} {ar?"بنود أسعار":"pricing lines"}</span></div></div></td>
  <td><div className="rx-pf">{o.platforms.map(platform=><i key={platform} title={taxonomyLabel(platform,lang)} aria-label={taxonomyLabel(platform,lang)} className={platform==="instagram"?"ig":platform==="tiktok"?"tt":platform==="facebook"?"fb":"yt"}>{({instagram:"IG",tiktok:"TT",facebook:"FB",youtube:"YT",snapchat:"SC"} as Record<string,string>)[platform]??platform}</i>)}</div></td>
  <td className="rx-cell-priv">{price(row.base.cost,"creator_cost",row.type,!!row.type)}</td><td>{price(row.base.client,"client_price",row.type,!!row.type)}</td><td className="rx-cell-priv rx-number">{pct(gp)}</td><td className="rx-cell-priv rx-number">{pct(markup)}</td><td className="rx-number">{o.agencyFeePct==null?tr("notSet"):formatPct(o.agencyFeePct)}{!fee.uniform&&<button className="rx-link" onClick={()=>toggle(o.id)}>{ar?"تختلف حسب الخدمة":"Varies by service"}</button>}</td>
  <td><div className="rx-extras">{extras.filter(e=>e.data).map(e=><button key={e.key} className={`rx-x rx-x--${e.cls}`} onClick={()=>toggle(o.id)} aria-expanded={open}>{e.label} <b>{quantity(e.pair,e.key==="event_attendance")}</b></button>)}{!extras.some(e=>e.data)&&row.includeExtras&&<button className="rx-x rx-x--add" onClick={()=>toggle(o.id)}>{editable?tr("xAdd"):(ar?"خدمات اختيارية":"Optional services")}</button>}</div></td>
  <td><div className="rx-row-actions"><button className="rx-b rx-b--sm" onClick={()=>toggle(o.id)} aria-expanded={open} aria-label={`${t("view")} ${o.creatorName}`}>{open?"−":"+"}</button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="rx-b rx-b--icon" aria-label={`${t("action")} ${o.creatorName}`}>⋯</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>onOfferAction(row.line,"details")}>{ar?"تفاصيل المبدع":"View creator details"}</DropdownMenuItem><DropdownMenuItem disabled={!editable} onClick={()=>onOfferAction(row.line,"urls")}>{ar?"إضافة رابط حساب":"Add profile URL"}</DropdownMenuItem><DropdownMenuItem disabled={!editable} onClick={()=>onOfferAction(row.line,"replace")}>{ar?"استبدال المبدع":"Replace creator"}</DropdownMenuItem><DropdownMenuItem disabled={!editable||!row.type} onClick={()=>onOfferAction(row.line,"deliverable")}>{ar?"تعديل نوع المحتوى / الباقة":"Edit deliverable / package"}</DropdownMenuItem><DropdownMenuItem disabled={!editable} onClick={()=>onEdit({...row.line,id:undefined,package_key:"",package_details:null,deliverable:"",amount:undefined,notes:""})}>{ar?"إضافة نوع محتوى":"Add deliverable"}</DropdownMenuItem><DropdownMenuItem disabled={!editable} className="text-destructive" onClick={()=>onRemove(row.ids,o.creatorName)}>{ar?"حذف العرض بالكامل…":"Delete complete offer…"}</DropdownMenuItem><DropdownMenuItem disabled={!editable} onClick={()=>onAvatar(row.line)}>{t("avatar")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></td></tr>
  {open&&<tr><td colSpan={10} className="rx-expanded-cell"><div className="rx-exp">{row.includeExtras&&extras.map(e=><section className="rx-sec" key={e.key}><div className="rx-sec__h"><b>{e.label}</b><span className="rx-sp"/><span className="rx-p">{quantity(e.pair,e.key==="event_attendance")}</span></div>
   {([['creator_cost',e.pair.cost],['client_price',e.pair.client]] as const).map(([kind,rate])=><div className={`rx-kv ${kind==="creator_cost"?"rx-cell-priv":""}`} key={kind}><span>{t(kind)} · {e.key==="event_attendance"?(ar?"يومي":"per day"):(ar?"شهري":"per month")}{kind==="creator_cost"&&<small>{ar?"داخلي · خاص":"Internal · private"}</small>}</span>{price(rate,kind,e.key)}</div>)}
   {e.data&&<><div className="rx-kv"><span>{ar?"مدة تكلفة المبدع":"Creator quantity"}</span><span>{e.data.creatorQty??tr("notSet")}</span></div><div className="rx-kv"><span>{ar?"مدة سعر العميل":"Client quantity"}</span><span>{e.data.clientQty??tr("notSet")}</span></div><div className="rx-kv is-total"><span>{tr("totalClient")}</span>{money(periodicTotal(e.data.client,e.data.clientQty))}</div><div className="rx-kv"><span>{t("agencyFee")}</span><span>{e.data.agencyFeePct==null?tr("notSet"):formatPct(e.data.agencyFeePct)}</span></div></>}
  </section>)}<section className="rx-sec"><div className="rx-sec__h"><b>{tr("tuT")}</b></div>{travelFields.map(f=><div className="rx-kv" key={f.key}><span title={f.label}>{f.short}</span><TravelUpliftCell field={f} value={row.line[f.key]} editable={editable} onSave={values=>onTravel(row.line,values)}/></div>)}<p className="rx-note">{tr("tuNote")}</p></section><section className="rx-sec rx-sec--priv"><div className="rx-sec__h"><b>{tr("intT")}</b></div><p>{tr("neverExported")}</p><p className="rx-note">{o.notes??tr("notSet")}</p><p className="rx-note">{tr("intNote")}</p></section></div></td></tr>}
  </Fragment>;
 })}</tbody></table></div>{!visible.length&&<div className="rx-empty"><b>{t("noLines")}</b>{view!=="all"&&<button className="rx-b" onClick={()=>setView("all")}>{tr("reset2")}</button>}</div>}<div className="rx-pg"><span>{visible.length} {ar?"عروض في الصفحة الحالية":"offers on this page"} · {ids.length} {ar?"بنود أسعار":"pricing lines"}</span></div></div></>;
}
