"use client";
import {useState} from "react";
import {Button} from "@/components/ui/button";
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger,DropdownMenuLabel,DropdownMenuSeparator} from "@/components/ui/dropdown-menu";
import {Choice,TextField,Pager} from "./ui";
import {rxText,textFor} from "./labels";
import {RATE_PLATFORM_OPTIONS} from "./platforms";
import {RateLanguage,RateSkeleton} from "./redesign-ui";
import type {RateCardRegisterProps,RegisterFilters,SortField} from "./types";

type Props=RateCardRegisterProps&{clients:{id:string;name:string}[];brands:{id:string;name:string;client_id:string}[];currencies:string[];canCreate:boolean;canUpload:boolean;busy:boolean;onUpload:()=>void};
export function RateCardRegister(p:Props){
 const [advanced,setAdvanced]=useState(false);const {lang,filters:f}=p;const t=(k:Parameters<typeof rxText>[1])=>rxText(lang,k);const old=(k:Parameters<typeof textFor>[1])=>textFor(lang,k);
 const change=(key:keyof RegisterFilters,value:string)=>p.onFiltersChange({...f,[key]:value||null,...(key==="clientId"?{brandId:null}:{})});
 const reset=()=>p.onFiltersChange({search:"",clientId:null,brandId:null,creatorQuery:"",status:null,version:null,platform:null,currency:null});
 const filterLabels:Record<keyof RegisterFilters,string>={search:old("search"),clientId:old("client"),brandId:old("brand"),creatorQuery:old("creator"),status:old("status"),version:old("version"),platform:old("platform"),currency:old("currency")};
 const caption=(key:string,value:string)=>key==="clientId"?p.clients.find(c=>c.id===value)?.name??value:key==="brandId"?p.brands.find(b=>b.id===value)?.name??value:key==="status"?old(value as "active"|"inactive"):value;
 const date=(v:string)=>new Date(v).toLocaleDateString(lang==="ar"?"ar-EG-u-nu-latn":"en-GB",{day:"2-digit",month:"short",year:"2-digit"});
 return <><header className="rx-ph"><div className="rx-ph__in"><div><h1>{t("p1Title")}</h1><p>{t("p1Sub")}</p></div><span className="rx-sp"/><RateLanguage lang={lang} onChange={p.onLangChange}/><Button className="rx-b" variant="outline" onClick={p.onRefresh} disabled={p.busy}>{old("reload")}</Button>
  <DropdownMenu><DropdownMenuTrigger asChild><Button className="rx-b" variant="outline">{t("tools")}</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{t("mgDownload")}</DropdownMenuLabel><DropdownMenuItem onClick={()=>p.onDownloadTemplate("individual")}>{t("tplInd")}</DropdownMenuItem><DropdownMenuItem onClick={()=>p.onDownloadTemplate("packages")}>{t("tplPkg")}</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem disabled={!p.canUpload||p.busy} onClick={p.onUpload}>{t("aUpload2")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>
  <Button className="rx-b rx-b--pri" disabled={!p.canCreate||p.busy} onClick={p.onCreate}>{t("create")}</Button></div></header>
 <div className="rx-wrap"><div className="rx-stats"><div className="rx-stat"><u>{t("s1a")}</u><b>{p.counts.matchingVersions}</b><span className="sub">{lang==="ar"?"كل النتائج المطابقة للفلاتر":"Across all matching results"}</span></div><div className="rx-stat"><u>{t("s1b")}</u><b>{p.counts.activeOnPage}</b><em>{lang==="ar"?`من ${p.rows.length} معروضة`:`of ${p.rows.length} shown`}</em><span className="sub">{t("s1bSub")}</span></div><div className="rx-stat"><u>{t("s1c")}</u><b className="rx-scope-name">{p.counts.scopeLabel}</b></div></div>
 <form className="rx-filters" onSubmit={e=>e.preventDefault()}><div className="rx-fbar rx-formbar">
  <TextField label={old("search")} value={f.search??""} onChange={v=>change("search",v)}/><Choice label={old("client")} value={f.clientId??""} onChange={v=>change("clientId",v)} options={p.clients.map(c=>({value:c.id,label:c.name}))}/><Choice label={old("status")} value={f.status??""} onChange={v=>change("status",v)} options={["active","inactive"].map(v=>({value:v,label:old(v as "active"|"inactive")}))}/>
  <Choice label={old("sort")} value={p.sort.field} onChange={v=>p.onSortChange(v as SortField,p.sort.dir)} empty={false} options={([["name","name"],["version","version"],["createdAt","created"],["updatedAt","updated"],["creatorCount","creators"],["clientName","client"]] as const).map(([value,k])=>({value,label:old(k)}))}/><Choice label={old("sortOrder")} value={p.sort.dir} onChange={v=>p.onSortChange(p.sort.field,v as "asc"|"desc")} empty={false} options={[{value:"desc",label:old("descending")},{value:"asc",label:old("ascending")}]}/><Button type="button" className="rx-b" variant="outline" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}>{t("more")}</Button></div>
  {advanced&&<div className="rx-adv"><Choice label={old("brand")} value={f.brandId??""} disabled={!f.clientId} onChange={v=>change("brandId",v)} options={p.brands.filter(b=>b.client_id===f.clientId).map(b=>({value:b.id,label:b.name}))}/><TextField label={old("creator")} value={f.creatorQuery??""} onChange={v=>change("creatorQuery",v)}/><TextField label={old("version")} value={f.version??""} onChange={v=>change("version",v)}/><Choice label={old("platform")} value={f.platform??""} onChange={v=>change("platform",v)} options={RATE_PLATFORM_OPTIONS}/><Choice label={old("currency")} value={f.currency??""} onChange={v=>change("currency",v)} options={p.currencies.map(c=>({value:c,label:c}))}/></div>}
  {Object.values(f).some(Boolean)&&<div className="rx-chips">{Object.entries(f).filter(([,v])=>v).map(([key,value])=><span className="rx-chip" key={key}>{filterLabels[key as keyof RegisterFilters]}: {caption(key,value!)}<button type="button" aria-label={`${old("remove")} ${filterLabels[key as keyof RegisterFilters]}`} onClick={()=>change(key as keyof RegisterFilters,"")}>×</button></span>)}<Button type="button" className="rx-b" variant="ghost" onClick={reset}>{t("reset")}</Button></div>}</form>
 <div className="rx-tbl" aria-busy={p.loading}>{p.loading?<RateSkeleton/>:p.rows.length?<div className="rx-scroll" tabIndex={0} role="region" aria-label={t("p1Title")}><table className="rx-register-table"><thead><tr>{["client","brand","name","version","status","created","updated","creators","action"].map(k=><th key={k}>{old(k as Parameters<typeof old>[0])}</th>)}</tr></thead><tbody>{p.rows.map(r=><tr key={r.id}>
 <td><div className="rx-id"><b title={r.clientName}>{r.clientName}</b></div></td><td><div className="rx-id"><b title={r.brandName??t("clientLevel")}>{r.brandName??t("clientLevel")}</b></div></td><td><button className="rx-link" title={r.name} onClick={()=>p.onOpenVersion(r.id)}>{r.name}</button><small>{r.currencies.join(" · ")}</small></td><td><span className="rx-p rx-p--blue">{r.version}</span></td><td><span className={`rx-p ${r.status==="active"?"rx-p--ok":""}`}>{old(r.status)}</span></td><td>{date(r.createdAt)}</td><td>{date(r.updatedAt)}</td><td className="rx-number">{r.creatorCount}</td><td><div className="rx-row-actions"><Button variant="outline" className="rx-b rx-b--sm" onClick={()=>p.onOpenVersion(r.id)}>{old("view")}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button className="rx-b rx-b--icon" variant="ghost" aria-label={`${old("action")} · ${r.name} · ${r.version}`}>⋯</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{t("mgManage")}</DropdownMenuLabel><DropdownMenuItem disabled={!p.permissions.canEditPricing||p.busy} onClick={()=>p.onEdit(r.id)}>{t("aEdit")}</DropdownMenuItem><DropdownMenuItem disabled={!p.canCreate||p.busy} onClick={()=>p.onDuplicate(r.id)}>{t("aDup")}</DropdownMenuItem><DropdownMenuItem disabled={!p.canUpload||p.busy} onClick={()=>p.onUploadInto(r.id)}>{t("aUpload")}</DropdownMenuItem><DropdownMenuItem disabled={!p.permissions.canActivate||p.busy} onClick={()=>p.onToggleActive(r.id,r.status==="active"?"inactive":"active")}>{old(r.status==="active"?"deactivate":"activate")}</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuLabel>{t("mgDanger")}</DropdownMenuLabel><DropdownMenuItem className="text-destructive" disabled={!p.permissions.canDeleteVersion||p.busy} onClick={()=>void p.onDeleteVersion(r.id)}>{lang==="ar"?"حذف هذا الإصدار فقط…":"Delete this version only…"}</DropdownMenuItem><DropdownMenuItem className="text-destructive" disabled={!p.permissions.canDeleteRateCard||p.busy} onClick={()=>void p.onDeleteRateCard(r.rateCardId)}>{t("aDelC")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></td>
 </tr>)}</tbody></table></div>:<div className="rx-empty"><b>{t("eTitle")}</b><u>{t("eBody")}</u><Button variant="outline" onClick={reset}>{t("reset2")}</Button></div>}
 <div className="rx-pg"><span>{t("perPage")}</span><span className="rx-sp"/><Pager page={p.page} total={p.totalRows} size={25} onChange={p.onPageChange} t={old}/></div></div></div></>;
}
