"use client";

import { useEffect, useState, useTransition } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { QuotationCreatorPicker } from "@/features/creators/picker/quotation-creator-picker";
import { DELIVERABLE_TYPES_BY_PLATFORM } from "@/lib/campaigns/deliverable-taxonomy";
import { SOCIAL_PLATFORM_OPTIONS } from "@/lib/master-data/constants";
import * as actions from "./actions";
import { RateCardAudit } from "./audit";
import { ReportControls } from "./report-controls";
import { PricingDialog } from "./pricing-dialog";
import {uploadForPreview,type UploadProgress} from "./upload-client";
import {EnrichmentProgress} from "./enrichment-progress";
import { headerSchema, rateSchema, type HeaderInput, type RateInput, type RateLine, type RateVersion, type ImportRow } from "./model";
import { errorLabel, taxonomyLabel, type Label } from "./labels";
import { Choice, Field, Modal, Pager, TextField, cell, useRateLanguage } from "./ui";

type Options=Awaited<ReturnType<typeof actions.rateCardOptions>>;
const initialHeader:HeaderInput={client_id:"",brand_id:null,name:"",version:"V1",status:"inactive",effective_date:null,expiry_date:null,notes:""};
export function RateCardsWorkspace({initialClient=""}:{initialClient?:string}) {
  const {lang,t,change}=useRateLanguage(); const [options,setOptions]=useState<Options|null>(null); const [error,setError]=useState<Label|null>(null);
  const [filters,setFilters]=useState({search:"",client:initialClient,brand:"",creator:"",status:"",version:"",platform:"",currency:"",sort:"updated_at",ascending:false,page:1});
  const [rows,setRows]=useState<RateVersion[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [revision,setRevision]=useState(0);
  const [editor,setEditor]=useState<{header:HeaderInput;id?:string;copyId?:string;expected?:string}|null>(null);
  const [detail,setDetail]=useState<string|null>(null);const [upload,setUpload]=useState<RateVersion|null>(null);const [confirm,setConfirm]=useState<{row:RateVersion;action:"delete"|"delete_card"}|null>(null);
  const [busy,start]=useTransition();
  useEffect(()=>{actions.rateCardOptions().then(setOptions).catch(e=>setError(errorLabel(e)));},[]);
  useEffect(()=>{let live=true;const timer=setTimeout(()=>{setLoading(true);actions.listRateCards(filters).then(r=>{if(live){setRows(r.rows);setTotal(r.total);setError(null);}}).catch(e=>live&&setError(errorLabel(e))).finally(()=>live&&setLoading(false));},250);return()=>{live=false;clearTimeout(timer);};},[filters,revision]);
  function update(key:keyof typeof filters,value:string|boolean){setFilters(f=>({...f,[key]:value,page:1,...(key==="client"?{brand:""}:{})}));}
  function run(work:()=>Promise<unknown>){start(async()=>{try{await work();setRevision(x=>x+1);toast.success(t("saved"));}catch(e){toast.error(t(errorLabel(e)));}});}
  async function template(){const b64=await actions.downloadRateTemplate();const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([Uint8Array.from(atob(b64),c=>c.charCodeAt(0))],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}));a.download="Thinkway-Rate-Card.xlsx";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  return <section dir={lang==="ar"?"rtl":"ltr"} lang={lang} className="space-y-5 p-4 md:p-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{t("title")}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{t("optional")}</p></div><Button variant="outline" onClick={()=>change(lang==="ar"?"en":"ar")}>{lang==="ar"?"English":"العربية"}</Button></header>
    <div className="flex flex-wrap gap-2"><Button disabled={!options?.permissions.create||busy} onClick={()=>setEditor({header:{...initialHeader,client_id:filters.client}})}>{t("create")}</Button><Button variant="outline" disabled={!options||busy} onClick={()=>run(template)}>{t("template")}</Button><Button variant="outline" disabled={!options?.permissions.upload} onClick={()=>{if(rows.length===1)setUpload(rows[0]);else setDetail("upload-select");}}>{t("upload")}</Button><Button variant="ghost" onClick={()=>setRevision(x=>x+1)}>{t("reload")}</Button></div>
    {error&&<p role="alert" className="rounded-md border border-destructive p-3 text-destructive">{t(error)}</p>}
    <form onSubmit={e=>e.preventDefault()} className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4">
      <TextField label={t("search")} value={filters.search} onChange={v=>update("search",v)}/><Choice label={t("client")} value={filters.client} onChange={v=>update("client",v)} options={options?.clients.map(c=>({value:c.id,label:c.name}))??[]}/><Choice label={t("brand")} value={filters.brand} onChange={v=>update("brand",v)} options={options?.brands.filter(b=>!filters.client||b.client_id===filters.client).map(b=>({value:b.id,label:b.name}))??[]}/><TextField label={t("creator")} value={filters.creator} onChange={v=>update("creator",v)}/>
      <Choice label={t("status")} value={filters.status} onChange={v=>update("status",v)} options={["active","inactive"].map(v=>({value:v,label:t(v as Label)}))}/><TextField label={t("version")} value={filters.version} onChange={v=>update("version",v)}/><Choice label={t("platform")} value={filters.platform} onChange={v=>update("platform",v)} options={SOCIAL_PLATFORM_OPTIONS.map(p=>({...p,label:taxonomyLabel(p.value,lang,p.label)}))}/><Choice label={t("currency")} value={filters.currency} onChange={v=>update("currency",v)} options={options?.currencies.map(c=>({value:c,label:c}))??[]}/>
      <Choice label={t("sort")} value={filters.sort} onChange={v=>update("sort",v)} empty={false} options={[["name","name"],["version","version"],["created_at","created"],["updated_at","updated"],["creator_count","creators"],["client_name","client"]].map(([value,k])=>({value,label:t(k as Label)}))}/><Choice label={t("sort")} value={String(filters.ascending)} onChange={v=>update("ascending",v==="true")} empty={false} options={[{value:"true",label:t("ascending")},{value:"false",label:t("descending")}]}/>
    </form>
    <div aria-busy={loading} className="overflow-x-auto rounded-xl border"><table className="w-full"><thead className="bg-muted"><tr>{["client","brand","name","version","status","created","updated","creators","currency","action"].map(k=><th key={k} className={cell}>{t(k as Label)}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className={cell}>{r.client_name}</td><td className={cell}>{r.brand_name??t("clientLevel")}</td><td className={cell}><button className="text-start font-medium underline underline-offset-4" onClick={()=>setDetail(r.id)}>{r.name}</button></td><td className={cell}>{r.version}</td><td className={cell}>{t(r.status)}</td><td className={cell}>{new Date(r.created_at).toLocaleDateString(lang)}</td><td className={cell}>{new Date(r.updated_at).toLocaleDateString(lang)}</td><td className={cell}>{r.creator_count}</td><td className={cell}>{r.currencies.join(" · ")}</td><td className={cell}><div className="flex flex-wrap gap-2">
      <Button size="sm" variant="outline" onClick={()=>setDetail(r.id)}>{t("view")}</Button>{options?.permissions.edit&&<Button size="sm" variant="outline" onClick={()=>setEditor({header:r,id:r.id,expected:r.updated_at})}>{t("edit")}</Button>}{options?.permissions.create&&<Button size="sm" variant="outline" onClick={()=>setEditor({header:{...r,version:"",status:"inactive"},copyId:r.id,expected:r.updated_at})}>{t("duplicate")}</Button>}{options?.permissions.upload&&<Button size="sm" variant="outline" onClick={()=>setUpload(r)}>{t("upload")}</Button>}{options?.permissions.activate&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>run(()=>actions.mutateRateVersion(r.id,r.status==="active"?"deactivate":"activate",r.updated_at))}>{t(r.status==="active"?"deactivate":"activate")}</Button>}{options?.permissions.delete&&<><Button size="sm" variant="outline" onClick={()=>setConfirm({row:r,action:"delete"})}>{t("delete")}</Button><Button size="sm" variant="outline" onClick={()=>setConfirm({row:r,action:"delete_card"})}>{t("deleteCard")}</Button></>}
    </div></td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-muted-foreground">{t(loading?"loading":"empty")}</p>}</div>
    <Pager page={filters.page} total={total} size={25} onChange={page=>setFilters(f=>({...f,page}))} t={t}/>
    {editor&&options&&<Modal open onClose={()=>setEditor(null)} title={t(editor.id?"edit":editor.copyId?"duplicate":"create")} description={t(editor.id||editor.copyId?"editScope":"optional")} lang={lang}><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();if(!headerSchema.safeParse(editor.header).success){toast.error(t("invalid"));return;}run(async()=>{const id=await actions.saveRateVersion(editor.header,editor.id,editor.copyId,editor.expected);setEditor(null);setDetail(id);});}}>
      <Choice label={t("client")} value={editor.header.client_id} disabled={!!editor.id||!!editor.copyId} onChange={v=>setEditor({...editor,header:{...editor.header,client_id:v,brand_id:null}})} options={options.clients.map(c=>({value:c.id,label:c.name}))}/><Choice label={t("brand")} value={editor.header.brand_id??""} disabled={!!editor.id||!!editor.copyId} onChange={v=>setEditor({...editor,header:{...editor.header,brand_id:v||null}})} options={options.brands.filter(b=>b.client_id===editor.header.client_id).map(b=>({value:b.id,label:b.name}))}/>
      {([['name','name'],['version','version'],['effective_date','effective'],['expiry_date','expiry'],['notes','notes']] as const).map(([key,label])=><TextField key={key} label={t(label)} value={editor.header[key]??""} type={key.endsWith("date")?"date":"text"} onChange={v=>setEditor({...editor,header:{...editor.header,[key]:key.endsWith("date")?v||null:v}})}/>)}<Choice label={t("status")} value={editor.header.status} disabled={!options.permissions.activate} empty={false} onChange={v=>setEditor({...editor,header:{...editor.header,status:v as "active"|"inactive"}})} options={["inactive","active"].map(v=>({value:v,label:t(v as Label)}))}/><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={busy}>{t(busy?"busy":"save")}</Button><Button type="button" variant="outline" onClick={()=>setEditor(null)}>{t("cancel")}</Button></div>
    </form></Modal>}
    {detail==="upload-select"&&<Modal open onClose={()=>setDetail(null)} title={t("upload")} description={t("choose")} lang={lang}>{rows.map(r=><Button key={r.id} variant="outline" onClick={()=>{setDetail(null);setUpload(r);}}>{r.client_name} · {r.name} · {r.version}</Button>)}{!rows.length&&<p>{t("create")}</p>}</Modal>}
    {detail&&detail!=="upload-select"&&options&&<VersionDetail id={detail} options={options} onClose={()=>{setDetail(null);setRevision(x=>x+1);}} onUpload={setUpload}/>}
    {upload&&<UploadDialog version={upload} onClose={()=>setUpload(null)} onDone={id=>{setUpload(null);setDetail(id);setRevision(x=>x+1);}}/>}
    {confirm&&<Modal open onClose={()=>setConfirm(null)} title={t(confirm.action==="delete"?"delete":"deleteCard")} description={t("deleteConfirm")} lang={lang}><p>{confirm.row.name} · {confirm.row.version}</p><div className="flex gap-2"><Button variant="destructive" disabled={busy} onClick={()=>run(async()=>{await actions.mutateRateVersion(confirm.row.id,confirm.action,confirm.row.updated_at);setConfirm(null);})}>{t("delete")}</Button><Button variant="outline" onClick={()=>setConfirm(null)}>{t("cancel")}</Button></div></Modal>}
  </section>;
}

function VersionDetail({id,options,onClose,onUpload}:{id:string;options:Options;onClose:()=>void;onUpload:(r:RateVersion)=>void}) {
  const [pricing,setPricing]=useState(false);
  const {lang,t}=useRateLanguage();const [data,setData]=useState<Awaited<ReturnType<typeof actions.getRateVersion>>|null>(null);const [page,setPage]=useState(1);const [search,setSearch]=useState("");const [platform,setPlatform]=useState("");const [currency,setCurrency]=useState("");const [revision,setRevision]=useState(0);const [selected,setSelected]=useState<Set<string>>(new Set());const [edit,setEdit]=useState<Partial<RateLine>|null>(null);const [source,setSource]=useState<"all"|"discovery">("all");const [confirm,setConfirm]=useState(false);const [busy,start]=useTransition();const [error,setError]=useState<Label|null>(null);
  useEffect(()=>{let live=true;const timer=setTimeout(()=>actions.getRateVersion(id,page,search,platform,currency).then(r=>{if(live){setData(r);setSelected(new Set());setError(null);}}).catch(e=>live&&setError(errorLabel(e))),200);return()=>{live=false;clearTimeout(timer);};},[id,page,search,platform,currency,revision]);
  return <Modal open onClose={onClose} title={data?`${data.version.name} · ${data.version.version}`:t("loading")} description={t("rateHint")} lang={lang}>
    {error&&<p role="alert">{t(error)}</p>}{data&&<><div className="flex flex-wrap gap-3 text-sm"><span>{data.version.client_name} · {data.version.brand_name??t("clientLevel")}</span><span>{t(data.version.status)}</span><span>{t("effective")}: {data.version.effective_date??"—"}</span><span>{t("expiry")}: {data.version.expiry_date??"—"}</span></div><p className="text-sm">{data.version.notes}</p><div className="flex flex-wrap gap-2">{options.permissions.edit&&<><Button onClick={()=>{setSource("all");setEdit({});}}>{t("add")}</Button><Button variant="outline" onClick={()=>{setSource("discovery");setEdit({});}}>{t("discovery")}</Button><Button variant="outline" disabled={!selected.size} onClick={()=>setConfirm(true)}>{t("remove")} ({selected.size})</Button></>}{options.permissions.upload&&<Button variant="outline" onClick={()=>onUpload(data.version)}>{t("upload")}</Button>}</div>
      <div className="grid gap-3 sm:grid-cols-3"><TextField label={t("search")} value={search} onChange={v=>{setSearch(v);setPage(1);}}/><Choice label={t("platform")} value={platform} options={SOCIAL_PLATFORM_OPTIONS.map(p=>({...p,label:taxonomyLabel(p.value,lang,p.label)}))} onChange={v=>{setPlatform(v);setPage(1);}}/><Choice label={t("currency")} value={currency} options={options.currencies.map(c=>({value:c,label:c}))} onChange={v=>{setCurrency(v);setPage(1);}}/></div>
      <div className="overflow-x-auto rounded-lg border"><table className="w-full"><thead className="bg-muted"><tr>{["select","creator","platform","deliverable","priceType","amount","currency","gp","markup","agencyFee","notes","action"].map(k=><th className={cell} key={k}>{t(k as Label)}</th>)}</tr></thead><tbody>{data.lines.map(l=><tr className="border-t" key={l.id}><td className={cell}><input aria-label={`${t("select")} ${l.creator_name}`} type="checkbox" checked={selected.has(l.id)} onChange={()=>setSelected(s=>{const n=new Set(s);if(n.has(l.id))n.delete(l.id);else n.add(l.id);return n;})}/></td><td className={cell}>{l.creator_name}<small className="block text-muted-foreground" dir="ltr">{l.creator_ref}</small></td><td className={cell}>{taxonomyLabel(l.platform??"",lang)}</td><td className={cell}>{taxonomyLabel(l.deliverable??"",lang)}</td><td className={cell}>{t(l.price_type)}</td><td className={cell}>{Number(l.amount).toLocaleString(lang)}</td><td className={cell}>{l.currency}</td><td className={cell}>{l.gp_percent==null?"—":Number(l.gp_percent).toFixed(2)+"%"}</td><td className={cell}>{l.markup_percent==null?"—":Number(l.markup_percent).toFixed(2)+"%"}</td><td className={cell}>{l.agency_fee_percent==null?"—":l.agency_fee_percent+"%"}</td><td className={cell}>{l.notes}</td><td className={cell}>{options.permissions.edit&&<Button variant="outline" size="sm" onClick={()=>setEdit(l)}>{t("edit")}</Button>}</td></tr>)}</tbody></table>{!data.lines.length&&<p className="p-6 text-center">{t("noLines")}</p>}</div><Pager page={page} total={data.total} size={50} onChange={setPage} t={t}/>
      <Button variant="outline" onClick={()=>setSelected(new Set(data.lines.map(l=>l.id)))}>{t("select")} · {t("all")}</Button>
      <ReportControls versionId={id}/><RateCardAudit versionId={id}/>
      {options.permissions.edit&&<Button variant="outline" onClick={()=>setPricing(true)}>{t("pricing")}</Button>}
      {pricing&&<PricingDialog versionId={id} onClose={()=>setPricing(false)} onDone={()=>{setPricing(false);setRevision(x=>x+1);}}/>}
      {edit&&<LineEditor initial={edit} options={options} source={source} onClose={()=>setEdit(null)} onSave={async value=>{await actions.saveRateLine(id,value,edit.id);setEdit(null);setRevision(x=>x+1);}}/>}
      {confirm&&<Modal open onClose={()=>setConfirm(false)} title={t("remove")} description={t("removeConfirm")} lang={lang}><Button disabled={busy} variant="destructive" onClick={()=>start(async()=>{try{await actions.removeRateLines(id,[...selected]);setConfirm(false);setRevision(x=>x+1);}catch(e){toast.error(t(errorLabel(e)));}})}>{t("remove")}</Button></Modal>}
    </>}
  </Modal>;
}
function LineEditor({initial,options,source,onClose,onSave}:{initial:Partial<RateLine>;options:Options;source:"all"|"discovery";onClose:()=>void;onSave:(r:RateInput)=>Promise<void>}) {
  const {lang,t}=useRateLanguage();const [rate,setRate]=useState<RateInput>({creator_ref:initial.creator_ref??"",creator_name:initial.creator_name??"",platform:initial.platform??"",deliverable:initial.deliverable??"",amount:initial.amount??0,currency:initial.currency??"",notes:initial.notes??"",price_type:initial.price_type??"creator_cost",agency_fee_percent:initial.agency_fee_percent??null});const [amount,setAmount]=useState(initial.amount==null?"":String(initial.amount));const [query,setQuery]=useState("");const [page,setPage]=useState(1);const [creators,setCreators]=useState<{id:string;label:string}[]>([]);const [loading,setLoading]=useState(false);const [busy,start]=useTransition();
  useEffect(()=>{let live=true;const timer=setTimeout(()=>{setLoading(true);actions.searchRateCreators(query,page,source).then(c=>live&&setCreators(c)).catch(e=>toast.error(t(errorLabel(e)))).finally(()=>live&&setLoading(false));},300);return()=>{live=false;clearTimeout(timer);};},[query,page,source,t]);
  return <Modal open onClose={onClose} title={t(initial.id?"edit":source==="discovery"?"discovery":"add")} description={t("rateHint")} lang={lang}><TextField label={t("search")} value={query} onChange={v=>{setQuery(v);setPage(1);}}/>
    <QuotationCreatorPicker hideToolbar loadingMessage={t("loading")} items={creators} loading={loading} emptyMessage={t("empty")} selectedIds={new Set(rate.creator_ref?[rate.creator_ref]:[])} onSelectedIdsChange={ids=>{const id=[...ids].find(i=>i!==rate.creator_ref)??[...ids][0];const c=creators.find(c=>c.id===id);if(c)setRate({...rate,creator_ref:c.id,creator_name:c.label});}}/>
    <div className="flex justify-between gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>{t("previous")}</Button><a className="text-sm underline" href="/vendors" target="_blank" rel="noreferrer">{t("newCreator")}</a><Button variant="outline" disabled={creators.length<20} onClick={()=>setPage(p=>p+1)}>{t("next")}</Button></div>
    <p className="font-medium">{rate.creator_name}</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const parsed=rateSchema.safeParse({...rate,amount:amount.trim()?Number(amount):NaN});if(!parsed.success){toast.error(t("invalid"));return;}start(async()=>{try{await onSave(parsed.data);}catch(e){toast.error(t(errorLabel(e)));}});}}><Choice label={t("platform")} value={rate.platform} options={SOCIAL_PLATFORM_OPTIONS.map(p=>({...p,label:taxonomyLabel(p.value,lang,p.label)}))} onChange={v=>setRate({...rate,platform:v,deliverable:""})}/><Choice label={t("deliverable")} value={rate.deliverable} options={(DELIVERABLE_TYPES_BY_PLATFORM[rate.platform]??[]).map(d=>({value:d.value,label:taxonomyLabel(d.value,lang,d.label)}))} onChange={v=>setRate({...rate,deliverable:v})}/><Choice label={t("priceType")} value={rate.price_type} empty={false} options={[{value:"creator_cost",label:t("creator_cost")},{value:"client_price",label:t("client_price")}]} onChange={v=>setRate({...rate,price_type:v as "creator_cost"|"client_price"})}/><TextField label={t("agencyFee")} type="number" value={rate.agency_fee_percent==null?"":String(rate.agency_fee_percent)} onChange={v=>setRate({...rate,agency_fee_percent:v===""?null:Number(v)})}/><TextField label={t("amount")} type="number" value={amount} onChange={setAmount}/><Choice label={t("currency")} value={rate.currency} options={options.currencies.map(c=>({value:c,label:c}))} onChange={v=>setRate({...rate,currency:v})}/><TextField label={t("notes")} value={rate.notes} onChange={v=>setRate({...rate,notes:v})}/><div className="flex items-end gap-2"><Button disabled={busy} type="submit">{t(busy?"busy":"save")}</Button><Button type="button" variant="outline" onClick={onClose}>{t("cancel")}</Button></div></form>
  </Modal>;
}
function UploadDialog({version,onClose,onDone}:{version:RateVersion;onClose:()=>void;onDone:(id:string)=>void}) {
  const {lang,t}=useRateLanguage();const [file,setFile]=useState<File|null>(null);const [rows,setRows]=useState<ImportRow[]|null>(null);const [mode,setMode]=useState<"new"|"update">("new");const [name,setName]=useState("");const [page,setPage]=useState(1);const [group,setGroup]=useState("");const [busy,start]=useTransition();
  const [progress,setProgress]=useState<UploadProgress|null>(null);const [created,setCreated]=useState<{id:string;name:string;created:boolean;queued:boolean}[]>([]);const [imported,setImported]=useState<string|null>(null);
  const form=()=>{const data=new FormData();if(file)data.set("file",file);return data;};const filtered=rows?.filter(r=>!group||r.status===group)??[];
  return <Modal open onClose={()=>!busy&&onClose()} title={`${t("upload")} · ${version.name} · ${version.version}`} description={t("importHelp")} lang={lang}><Field label={t("file")}><Input type="file" accept=".xlsx" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);setRows(null);setCreated([]);setImported(null);setProgress(null);}}/></Field><Button disabled={!file||busy} onClick={()=>start(async()=>{try{setRows(await uploadForPreview(form(),setProgress));setProgress(null);setPage(1);}catch(e){setProgress(null);toast.error(t(errorLabel(e)));}})}>{t(busy?"loading":"preview")}</Button>
    {progress&&<div role="status" aria-live="polite"><p>{t(progress.stage)} {progress.total>0?`${progress.processed} / ${progress.total} · ${Math.round(progress.processed/progress.total*100)}%`:"…"}</p><progress className="w-full" max={progress.total||1} value={progress.total?progress.processed:undefined}/></div>}<EnrichmentProgress creators={created}/>{imported&&<div role="status"><p>{t("imported")}: {rows?.length}</p><Button onClick={()=>onDone(imported)}>{t("view")}</Button></div>}
    {rows&&!imported&&<><p>{t("matched")}: {rows.filter(r=>r.rate&&!r.pending_creator).length} / {rows.length}</p><div className="flex flex-wrap gap-2">{([['ready','ready'],['warning','warning'],['error','errors'],['unmatched','unmatchedGroup']] as const).map(([value,key])=><Button variant={group===value?"default":"outline"} key={value} onClick={()=>{setGroup(group===value?"":value);setPage(1);}}>{t(key)}: {rows.filter(r=>r.status===value).length}</Button>)}</div><div className="overflow-x-auto"><table className="w-full"><thead><tr>{["row","creator","platform","deliverable","creator_cost","client_price","gp","markup","agencyFee","status"].map(k=><th key={k} className={cell}>{t(k as Label)}</th>)}</tr></thead><tbody>{filtered.slice((page-1)*50,page*50).map(r=><tr key={r.row} className="border-t"><td className={cell}>{r.row}</td><td className={cell}>{r.rate?.creator_name}</td><td className={cell}>{taxonomyLabel(r.rate?.platform??"",lang)}</td><td className={cell}>{taxonomyLabel(r.rate?.deliverable??"",lang)}</td><td className={cell}>{(r.rates??[r.rate]).filter(x=>x?.price_type==="creator_cost").map(x=>x!.currency+" "+x!.amount).join(" · ")||"—"}</td><td className={cell}>{(r.rates??[r.rate]).filter(x=>x?.price_type==="client_price").map(x=>x!.currency+" "+x!.amount).join(" · ")||"—"}</td><td className={cell}>{r.gp_percent==null?"—":r.gp_percent.toFixed(2)+"%"}</td><td className={cell}>{r.markup_percent==null?"—":r.markup_percent.toFixed(2)+"%"}</td><td className={cell}>{r.rate?.agency_fee_percent==null?"—":r.rate.agency_fee_percent+"%"}</td><td className={cell}>{r.issues.map(i=>t(i==="duplicate"?"duplicateError":i==="currency"?"currencyError":i as Label)).join(" · ")||t("ready")}</td></tr>)}</tbody></table></div><Pager page={page} total={filtered.length} size={50} onChange={setPage} t={t}/><Choice label={t("import")} value={mode} empty={false} onChange={v=>setMode(v as "new"|"update")} options={[{value:"new",label:t("newVersion")},{value:"update",label:t("updateVersion")}]}/>{mode==="new"?<TextField label={t("version")} value={name} onChange={setName}/>:<p role="status">{t("updatedRows")}</p>}<Button disabled={busy||rows.some(r=>r.status==="error"||r.status==="unmatched")||(mode==="new"&&!name.trim())} onClick={()=>start(async()=>{try{const candidates=[...new Set(rows.flatMap(r=>r.pending_creator?[r.pending_creator.profile_url]:[]))];
      for(let i=0;i<candidates.length;i++){setProgress({stage:"creating",processed:i,total:candidates.length});const c=await actions.ensureImportCreator(candidates[i]);setCreated(previous=>previous.some(p=>p.id===c.id)?previous:[...previous,c]);setProgress({stage:"creating",processed:i+1,total:candidates.length});}
      setProgress({stage:"importing",processed:0,total:rows.length});
      const result=await actions.commitRateImport(form(),version.id,mode,mode==="new"?name:version.version,version.updated_at);setImported(result);setProgress({stage:"completed",processed:rows.length,total:rows.length});}catch(e){setProgress(null);toast.error(t(errorLabel(e)));}})}>{t(busy?"busy":"import")}</Button></>}
  </Modal>;
}
