/**
 * Campaign Outputs Engine — type vocabulary.
 *
 * A Campaign Output is a *generated view over the Campaign Object* (the Single
 * Source of Truth) — never a separate object and never duplicated data.
 *
 * Naming note: this is deliberately "Campaign Output", not "deliverable". In
 * agency/influencer language a *deliverable* is a creator asset (Reel, Story,
 * Static Post, YouTube integration). A *Campaign Output* is an artifact the
 * platform generates about the whole campaign (Strategy, Media Plan, Proposal,
 * KPI Forecast, …). The internal architecture uses "output" everywhere to avoid
 * that ambiguity; user-facing copy may still say "Generate Deliverables".
 *
 * The Campaign Outputs Engine is a platform capability, not a Studio feature:
 * the Studio *consumes* outputs; the Engine *generates* them; both read the same
 * Campaign Object.
 */

/** Every client-facing output the Engine can generate from a Campaign Object. */
export type CampaignOutputKind =
  | "full_strategy"
  | "executive_proposal"
  | "media_plan"
  | "content_calendar"
  | "posting_timeline"
  | "creator_activation"
  | "campaign_playbook"
  | "kpi_forecast"
  | "risk_plan"
  | "budget_allocation"
  | "amplification_plan"
  | "executive_summary"
  | "creative_concepts"
  | "client_presentation"
  | "statement_of_work"
  | "campaign_brief"
  | "internal_operations";

/**
 * The campaign inputs an output derives from. These drive the dependency graph:
 * when an input changes, every output that depends on it becomes "Needs Update".
 * Input keys are stable slices of the Campaign Object, not sections — several
 * outputs can share one input.
 */
export type CampaignOutputInputKey =
  | "brief"
  | "objective"
  | "audience"
  | "market"
  | "platforms"
  | "creators"
  | "budget"
  | "timeline"
  | "kpis"
  | "strategy"
  | "creative_concepts"
  | "risks"
  | "deliverables_scope"
  | "market_intelligence";

export type CampaignOutputStatus = "not_generated" | "generated" | "needs_update";

/** Fine-grained catalog category (kept for description/theming). */
export type CampaignOutputCategory =
  | "strategy"
  | "planning"
  | "performance"
  | "creative"
  | "presentation"
  | "operations";

/**
 * Top-level, metadata-driven grouping for the Campaign Outputs Center. Cards are
 * grouped by this — the Center never hardcodes which output goes where.
 */
export type CampaignOutputGroup = "strategy" | "planning" | "client" | "internal";

/** Who triggered a generation — shown on the card as "Generated by". */
export type CampaignOutputOrigin = "copilot" | "user" | "automatic";

/**
 * Media Plan (and future controlled artefacts) change class.
 * - revise: controlled patch — preserve creators/waves/deliverables/strategy/manual edits
 * - regenerate: strategic redesign — may reorder creators and rebuild the schedule
 * - restore: forward-restore of a prior snapshot
 * - initial: first generation of the artefact
 */
export type CampaignOutputOperation = "revise" | "regenerate" | "restore" | "initial";

/** Actor that produced a version — user vs AI vs system automation. */
export type CampaignOutputActorKind = "user" | "ai" | "system";

/**
 * Media Plan business-version lifecycle (SSOT: MEDIA_PLAN_VERSIONING.md).
 * Distinct from engine `MediaPlanStatus` — mapped in media-plan-versioning.ts.
 */
export type MediaPlanBusinessStatus =
  | "draft"
  | "under_review"
  | "approved"
  | "superseded"
  | "archived";

/** Who approved the business version. */
export type MediaPlanApprovalSource = "client" | "internal";

/**
 * Whether the next approval cycle needs client involvement.
 * `none` — initial / no re-approval signal yet.
 */
export type MediaPlanApprovalImpact = "none" | "internal" | "client_reapproval";

/**
 * Audit History entry — every modification. Never bumps the business version.
 * SSOT: Business Version vs Audit History are completely separate.
 */
export type MediaPlanAuditEntry = {
  at: string;
  actorKind: CampaignOutputActorKind;
  actorUserId?: string;
  reason: string;
  /** Compact before/after for reconstructability. */
  before?: unknown;
  after?: unknown;
  operationClass?: string;
};

/** One block of rendered output content — generic so any output renders/exports uniformly. */
export type CampaignOutputContentSection = {
  heading: string;
  body?: string;
  items?: string[];
  table?: { columns: string[]; rows: string[][] };
};

/**
 * The rendered, human-readable output. `data` carries the structured payload
 * (e.g. the Media Plan's week→day schedule) for richer rendering/export;
 * `sections` is always present so every output can be shown and exported the
 * same way.
 */
export type CampaignOutputContent = {
  title: string;
  summary?: string;
  sections: CampaignOutputContentSection[];
  data?: Record<string, unknown>;
};

/** A prior version of an output, kept for compare / restore / history. */
export type CampaignOutputVersionSnapshot = {
  /** Monotonic revision sequence (restore/compare key). */
  version: number;
  /** Enterprise major line (regenerate bumps). */
  versionMajor?: number;
  /** Enterprise minor revision within a major line (revise/restore bumps). */
  versionMinor?: number;
  /** Display label, e.g. "v1.2". */
  versionLabel?: string;
  operation?: CampaignOutputOperation;
  generatedAt?: string;
  updatedAt?: string;
  sourceFingerprint?: string;
  generatorVersion?: string;
  /** Why this version was (re)generated, e.g. "Creator slate changed". */
  changeReason?: string;
  /** Human change summary for audit / history. */
  changeSummary?: string;
  /** The campaign inputs that triggered this version. */
  changedInputs?: CampaignOutputInputKey[];
  origin?: CampaignOutputOrigin;
  actorKind?: CampaignOutputActorKind;
  actorUserId?: string;
  /** Media Plan business lifecycle status at the time of this snapshot. */
  businessStatus?: MediaPlanBusinessStatus;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvalSource?: MediaPlanApprovalSource | null;
  approvalImpact?: MediaPlanApprovalImpact;
  content?: CampaignOutputContent;
};

/**
 * The persisted registry entry for one output. It is metadata + a snapshot of
 * the generated view — never authoritative campaign data, only a derived
 * rendering plus the fingerprint of the inputs it came from and the version of
 * the generator that produced it.
 */
export type CampaignOutputRecord = {
  kind: CampaignOutputKind;
  status: CampaignOutputStatus;
  /**
   * Monotonic technical sequence for restore/compare keys.
   * For Media Plan: increments on **business version** boundaries only (not every audit edit).
   */
  version: number;
  /** Enterprise major line (Media Plan regenerate → v2.0, v3.0, …). */
  versionMajor?: number;
  /** Enterprise minor revision (Media Plan revise → v1.1, v1.2, …). */
  versionMinor?: number;
  /** Display label, e.g. "v1.2". */
  versionLabel?: string;
  /** Last operation that produced this record. */
  operation?: CampaignOutputOperation;
  generatedAt?: string;
  updatedAt?: string;
  /** Campaign Object version this output was generated from, when known. */
  campaignVersion?: number;
  /** Combined fingerprint of the source inputs at generation time — drives staleness. */
  sourceFingerprint?: string;
  /** Per-input fingerprints — let the Center name exactly which input went stale. */
  inputFingerprints?: Partial<Record<CampaignOutputInputKey, string>>;
  /** The generator's semantic version at generation time — for reproducibility/compare. */
  generatorVersion?: string;
  /** Who triggered this generation. */
  origin?: CampaignOutputOrigin;
  actorKind?: CampaignOutputActorKind;
  actorUserId?: string;
  /** Approximate size of the rendered view in bytes. */
  sizeBytes?: number;
  /** Why the current version was (re)generated. */
  changeReason?: string;
  /** Human change summary for audit / history. */
  changeSummary?: string;
  /** The campaign inputs that triggered the current version. */
  changedInputs?: CampaignOutputInputKey[];
  /**
   * Business version history only (milestones). Not every keystroke.
   * SSOT: separate from `auditHistory`.
   */
  history?: CampaignOutputVersionSnapshot[];
  /**
   * Media Plan Audit History — every modification; never bumps business version.
   */
  auditHistory?: MediaPlanAuditEntry[];
  /** Media Plan business lifecycle status for the current tip. */
  businessStatus?: MediaPlanBusinessStatus;
  approvedBy?: string | null;
  approvedAt?: string | null;
  approvalSource?: MediaPlanApprovalSource | null;
  approvalImpact?: MediaPlanApprovalImpact;
  /** The generated view, cached for View/Export without recomputation. */
  content?: CampaignOutputContent;
};

/** Why a generated output is out of date, named precisely from input diffs. */
export type CampaignOutputStaleReason = {
  staleInputs: CampaignOutputInputKey[];
  /** Human sentence, e.g. "Creator slate changed." — never a generic message. */
  reason: string;
};

/** The registry state stored on `CampaignObjectMeta.campaignOutputs`. */
export type CampaignOutputRegistryState = Partial<
  Record<CampaignOutputKind, CampaignOutputRecord>
>;
