"use server";
import {z} from 'zod';import {revalidatePath} from 'next/cache';import {createSupabaseServerClient} from '@/lib/supabase/server';import {planningDb} from '@/lib/supabase/governance-client';import {requireFinancePermission} from '@/lib/auth/permissions-server';
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
export async function recordVatPayment(form:FormData){
 const db=await createSupabaseServerClient();const auth=await requireFinancePermission(db,'finance.write');if('error' in auth)return {ok:false,error:auth.error};
 const parsed=z.object({request_id:z.string().uuid(),period:day.refine(v=>v.endsWith('-01')),country_code:z.string().regex(/^[A-Z]{2}$/),currency:z.string().regex(/^[A-Z]{3}$/),amount:z.coerce.number().positive().max(999999999999).refine(v=>Math.abs(v*100-Math.round(v*100))<0.00001),paid_at:day.refine(v=>v<=new Date().toISOString().slice(0,10)),method:z.enum(['bank_transfer','wire','check','cash','other']),reference:z.string().trim().min(1).max(120),authority:z.string().trim().min(1).max(200),notes:z.string().max(2000)}).safeParse(Object.fromEntries(form));
 if(!parsed.success)return {ok:false,error:'Check the amount, month, country code, actual payment date and reference.'};
 const {error}=await planningDb(db).from('vat_authority_payments').insert({...parsed.data,recorded_by:auth.userId});
 if(error&&error.code!=='23505')return {ok:false,error:'Could not record VAT payment. Check Finance write access and retry.'};
 revalidatePath('/finance/vat');revalidatePath('/');return {ok:true};
}
export async function saveCreatorInvoice(form:FormData){
 const db=await createSupabaseServerClient();const auth=await requireFinancePermission(db,'finance.write');if('error' in auth)return {ok:false,error:auth.error};
 const parsed=z.object({request_id:z.string().uuid(),assignment_id:z.string().uuid(),status:z.enum(['received','not_received','not_provided']),invoice_number:z.string().trim().max(120),invoice_date:z.string(),due_date:z.string(),country_code:z.string().regex(/^[A-Z]{2}$/),currency:z.string().regex(/^[A-Z]{3}$/),supplier_name:z.string().trim().min(1).max(200),supplier_address:z.string().max(1000),tax_registration_number:z.string().max(100),description:z.string().max(2000),subtotal:z.coerce.number().min(0).max(999999999999),vat_amount:z.coerce.number().min(0).max(999999999999),notes:z.string().max(2000)}).safeParse(Object.fromEntries(form));
 if(!parsed.success)return {ok:false,error:'Check the creator invoice details and country/currency codes.'};const v=parsed.data;
 if(v.status==='received'&&(!v.invoice_number||!day.safeParse(v.invoice_date).success||v.invoice_date>new Date().toISOString().slice(0,10)))return {ok:false,error:'A received invoice needs its number and actual invoice date.'};
 if(v.due_date&&(!day.safeParse(v.due_date).success||v.due_date<v.invoice_date))return {ok:false,error:'Due date must be valid and no earlier than invoice date.'};
 const {data:assignment}=await db.from('campaign_influencers').select('id').eq('id',v.assignment_id).maybeSingle();if(!assignment)return {ok:false,error:'Assignment unavailable.'};
 const editingId=String(form.get('invoice_id')||'');if(editingId&&!z.string().uuid().safeParse(editingId).success)return {ok:false,error:'Invalid invoice'};
 const existing=await planningDb(db).from('creator_supplier_invoices').select('id').eq('request_id',v.request_id).maybeSingle();if(!editingId&&existing.data)return {ok:true};
 let storage_path:string|null=null;const file=form.get('file');if(file instanceof File&&file.size){if(file.size>4194304||!['application/pdf','image/jpeg','image/png'].includes(file.type))return {ok:false,error:'Attach a PDF, JPG or PNG up to 4 MB.'};storage_path=`${auth.userId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const uploaded=await db.storage.from('creator-invoices').upload(storage_path,file,{contentType:file.type,upsert:false});if(uploaded.error)return {ok:false,error:'Attachment upload failed. Retry before saving.'};}
 const {error}=editingId?await planningDb(db).rpc('update_creator_invoice_details',{p_id:editingId,p_revision:Number(form.get('revision')),p_details:{supplier_name:v.supplier_name,supplier_address:v.supplier_address,tax_registration_number:v.tax_registration_number,description:v.description,notes:v.notes,due_date:v.due_date,storage_path}}):await planningDb(db).from('creator_supplier_invoices').insert({...v,invoice_number:v.status==='received'?v.invoice_number:null,invoice_date:v.status==='received'?v.invoice_date:null,due_date:v.due_date||null,confirmed:v.status==='received'&&form.get('confirmed')==='on',storage_path,recorded_by:auth.userId});
 if(error){if(storage_path)await db.storage.from('creator-invoices').remove([storage_path]);return {ok:false,error:error.code==='23505'?'This invoice number is already recorded for the assignment.':editingId?'Invoice details could not be saved. Refresh to check for newer changes.':'Could not save invoice. Check Finance access and retry.'};}
 for(const p of ['/billing','/billing/creator-invoices','/finance/vat','/'])revalidatePath(p);return {ok:true};
}
export async function confirmCreatorInvoice(id:string){const db=await createSupabaseServerClient();const auth=await requireFinancePermission(db,'finance.write');if('error' in auth)return {ok:false,error:auth.error};if(!z.string().uuid().safeParse(id).success)return {ok:false,error:'Invalid invoice'};const {error}=await planningDb(db).rpc('confirm_creator_supplier_invoice',{p_id:id});if(error)return {ok:false,error:'Could not confirm this invoice. Check Finance access.'};for(const p of ['/billing/creator-invoices','/finance/vat','/'])revalidatePath(p);return {ok:true};}
