export const OPERATIONAL_GRID_LABELS = {
  select: "",
  type: "Type",
  platform: "Plat",
  deliverableType: "Deliv type",
  postDate: "Date",
  qty: "Qty",
  revPerAd: "Rev/ad",
  costPerAd: "Cost/ad",
  rev: "Rev",
  cost: "Cost",
  vat: "VAT",
  billing: "Billing",
  invoice: "Inv",
  collection: "Coll",
  payout: "Payout",
  workflow: "WF",
  notes: "Notes",
  actions: "",
} as const;

export const GRID_CELL = {
  select: "w-8 px-1.5 py-1.5",
  type: "w-[88px] px-1.5 py-1.5",
  platform: "w-[52px] px-1.5 py-1.5",
  deliverableType: "min-w-[88px] px-1.5 py-1.5",
  postDate: "w-[104px] px-1.5 py-1.5",
  qty: "w-[44px] px-1.5 py-1.5 text-right font-mono",
  money: "w-[72px] px-1.5 py-1.5 text-right font-mono",
  vat: "w-[64px] px-1.5 py-1.5 text-right font-mono",
  status: "w-[80px] px-1.5 py-1.5",
  invoice: "w-[72px] px-1.5 py-1.5",
  collection: "w-[52px] px-1.5 py-1.5 text-[10px]",
  payout: "w-[64px] px-1.5 py-1.5",
  workflow: "w-[72px] px-1.5 py-1.5",
  notes: "min-w-[88px] max-w-[120px] px-1.5 py-1.5",
  actions: "w-[64px] px-1.5 py-1.5 text-right",
} as const;
