"use client";
import {useState,useTransition} from 'react';import {useRouter} from 'next/navigation';import {toast} from 'sonner';import {saveCreatorInvoice} from '@/features/finance/vat/ledger-actions';
export type CreatorInvoiceChoice={id:string;creator:string;campaign:string;currency:string;fee:number;country:string;io:string};
export function CreatorInvoiceForm({choices,initial}:{choices:CreatorInvoiceChoice[];initial:string}){
 const [previewTotal,setPreviewTotal]=useState<number|null>(null);const [assignment,setAssignment]=useState(initial||choices[0]?.id||'');const row=choices.find(r=>r.id===assignment);const [status,setStatus]=useState('received');const [pending,start]=useTransition();const [request,setRequest]=useState('');const router=useRouter();
 return <form onInput={e=>{const fd=new FormData(e.currentTarget);setPreviewTotal(Number(fd.get("subtotal")||0)+Number(fd.get("vat_amount")||0));}} className="rounded-xl border bg-white p-4 text-sm" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const id=request||crypto.randomUUID();setRequest(id);fd.set('request_id',id);start(async()=>{const r=await saveCreatorInvoice(fd);if(!r.ok)toast.error(r.error);else{toast.success('Creator invoice details saved.');setRequest('');router.refresh();}});}}><h2 className="mb-3 font-semibold">Add creator invoice / invoice status</h2><label>Creator · campaign<select className="mb-3 block w-full rounded border p-2" name="assignment_id" value={assignment} onChange={e=>{setAssignment(e.target.value);setPreviewTotal(null);setRequest('');}}>{choices.map(r=><option key={r.id} value={r.id}>{r.creator} · {r.campaign} · {r.currency} {r.fee}</option>)}</select></label><p className="mb-3">Vendor IO: {row?.io||'Not set'} · An invoice can be added after payment; this does not create another payment or change the agreed fee.</p>
 <div key={assignment} className="grid gap-3 sm:grid-cols-3"><label>Invoice status<select className="block w-full rounded border p-2" name="status" value={status} onChange={e=>setStatus(e.target.value)}><option value="received">Received</option><option value="not_received">Invoice not received</option><option value="not_provided">Not provided</option></select></label>
 {([['supplier_name','Supplier / legal name','text',row?.creator],['supplier_address','Supplier address','text',''],['tax_registration_number','Tax registration number','text',''],['invoice_number','Invoice number','text',''],['invoice_date','Invoice date','date',''],['due_date','Due date','date',''],['country_code','Tax country (EG / AE / SA)','text',row?.country],['currency','Invoice currency','text',row?.currency],['subtotal','Amount before VAT','number',row?.fee],['vat_amount','VAT amount','number',0],['description','Services / invoice description','text',''],['notes','Notes / reason no invoice','text','']] as const).map(([name,label,type,value])=><label key={name}>{label}<input className="block w-full rounded border p-2" name={name} type={type} defaultValue={value??''} required={['supplier_name','country_code','currency','subtotal','vat_amount'].includes(name)||(status==='received'&&['invoice_number','invoice_date'].includes(name))} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} maxLength={name==='country_code'?2:name==='currency'?3:undefined}/></label>)}
 <label>Invoice attachment (PDF, JPG, PNG · up to 4 MB)<input className="block w-full rounded border p-2" name="file" type="file" accept="application/pdf,image/jpeg,image/png"/></label></div>
 <p className="mt-4 font-semibold">Invoice total: {(previewTotal??row?.fee??0).toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2})}</p><label className="my-4 block"><input type="checkbox" name="confirmed" disabled={status!=='received'}/> I have reviewed this invoice and confirm its VAT should be included in the statement.</label><p className="mb-3 text-muted-foreground">Only received, confirmed invoices enter the VAT statement. Invoice dates determine the month, including old paid assignments. Keep unreceived or unreviewed documents out of confirmed VAT.</p><button className="rounded bg-blue-600 px-4 py-2 text-white" disabled={pending||!row}>{pending?'Saving…':'Save invoice details'}</button></form>;
}
