/** Finance control audit event keys (stored in audit_logs.metadata.event). */
export const FINANCE_AUDIT_EVENTS = {
  cn_created: "cn_created",
  cn_approved: "cn_approved",
  cn_posted: "cn_posted",
  cn_cancelled: "cn_cancelled",
  cn_unposted: "cn_unposted",
  cn_reopened: "cn_reopened",
  dn_created: "dn_created",
  dn_approved: "dn_approved",
  dn_posted: "dn_posted",
  dn_cancelled: "dn_cancelled",
  dn_unposted: "dn_unposted",
  dn_reopened: "dn_reopened",
  invoice_posted: "invoice_posted",
  invoice_unposted: "invoice_unposted",
  invoice_regenerated: "invoice_regenerated",
  invoice_voided: "invoice_voided",
  invoice_cancelled: "invoice_cancelled",
  campaign_cancelled: "campaign_cancelled",
  campaign_reopened: "campaign_reopened",
  vendor_io_cancelled: "vendor_io_cancelled",
  posting_created: "posting_created",
  posting_posted: "posting_posted",
  posting_reversed: "posting_reversed",
  erp_sync_sent: "erp_sync_sent",
  erp_sync_failed: "erp_sync_failed",
} as const;

export type FinanceAuditEvent =
  (typeof FINANCE_AUDIT_EVENTS)[keyof typeof FINANCE_AUDIT_EVENTS];

export const FINANCE_AUDIT_EVENT_LABELS: Record<FinanceAuditEvent, string> = {
  cn_created: "CN Created",
  cn_approved: "CN Approved",
  cn_posted: "CN Posted",
  cn_cancelled: "CN Cancelled",
  cn_unposted: "CN Unposted",
  cn_reopened: "CN Reopened",
  dn_created: "DN Created",
  dn_approved: "DN Approved",
  dn_posted: "DN Posted",
  dn_cancelled: "DN Cancelled",
  dn_unposted: "DN Unposted",
  dn_reopened: "DN Reopened",
  invoice_posted: "Invoice Posted",
  invoice_unposted: "Invoice Unposted",
  invoice_regenerated: "Invoice Regenerated",
  invoice_voided: "Invoice Voided",
  invoice_cancelled: "Invoice Cancelled",
  campaign_cancelled: "Campaign Cancelled",
  campaign_reopened: "Campaign Reopened",
  vendor_io_cancelled: "IO Cancelled",
  posting_created: "Posting Batch Created",
  posting_posted: "Posting Batch Posted",
  posting_reversed: "Posting Batch Reversed",
  erp_sync_sent: "ERP Sync Sent",
  erp_sync_failed: "ERP Sync Failed",
};
