"use client";
import { formatDocumentNumberForDisplay as documentLabel } from "@/lib/documents/format-document-number";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {toast} from "sonner";
import {deleteCollectionPayment,reviseCollectionPayment} from "../redesign-actions";
import {dateLabel,money,type CollectionPayment,type CollectionsPageData} from "../redesign-data";
export function CollectionPaymentHistory({payments,invoices}:{payments:CollectionPayment[];invoices:CollectionsPageData["invoices"]}) {
 const [search,setSearch]=useState("");const [edit,setEdit]=useState<CollectionPayment|null>(null);const [reason,setReason]=useState("");const [pending,start]=useTransition();const router=useRouter();
 const saving=useRef(false);const [deleting,setDeleting]=useState<CollectionPayment|null>(null);const [deleteReason,setDeleteReason]=useState("");
 const rows=payments.filter(p=>`${p.document_number} ${documentLabel(p.document_number)} ${documentLabel(invoices.find(i=>i.id===p.invoice_id)?.document_number)} ${invoices.find(i=>i.id===p.invoice_id)?.document_number} ${invoices.find(i=>i.id===p.invoice_id)?.client_name} ${p.reference_number}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="tw-c"><div className="tw-ch"><span className="tw-ct">Payment history</span><span className="tw-cs">Latest 1,000 receipts · corrections retain an audit trail</span><span className="tw-sp"/><input className="tw-in" style={{width:240}} aria-label="Find recorded payment" placeholder="Client, invoice or reference" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="tw-sc"><table className="w-full text-left text-xs"><thead><tr>{['Date','Client','Invoice','Payment','Currency','Amount','Method','Reference','Notes',''].map((h,i)=><th key={i} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(p=>{const inv=invoices.find(i=>i.id===p.invoice_id);return <tr key={p.id} className="border-t"><td className="p-3 whitespace-nowrap">{dateLabel(p.paid_at)}</td><td className="p-3">{inv?.client_name??'—'}</td><td className="p-3">{documentLabel(inv?.document_number)||'—'}</td><td className="p-3">{documentLabel(p.document_number)}</td><td className="p-3">{p.currency}</td><td className="p-3 tabular-nums">{money(p.amount)}</td><td className="p-3">{p.payment_method.replaceAll('_',' ')}</td><td className="p-3">{p.reference_number??'—'}</td><td className="p-3">{p.notes??'—'}</td><td className="p-3"><button className="tw-b sm" onClick={()=>{setDeleting(null);setEdit({...p});setReason('');}} disabled={pending || p.status!=='completed'}>Edit</button> {p.status==='completed'?<button className="tw-b sm" disabled={pending} onClick={()=>{setEdit(null);setDeleting(p);setDeleteReason('');}}>Delete</button>:<span className="tw-hint">{p.status==='cancelled'?'Deleted · audit retained':p.status}</span>}</td></tr>})}</tbody></table></div>{!rows.length&&<div className="tw-note">No recorded payments match. New receipts will appear here after recording.</div>}
 {edit&&<form data-payment-edit aria-busy={pending} className="tw-pad" onSubmit={e=>{e.preventDefault();if(saving.current || pending)return;saving.current=true;start(async()=>{try {const result=await reviseCollectionPayment({id:edit.id,revision:edit.revision,amount:edit.amount,date:edit.paid_at?.slice(0,10)??'',method:edit.payment_method,reference:edit.reference_number??'',notes:edit.notes??'',reason});if(!result.ok)toast.error(result.error);else{toast.success('Payment corrected. Invoice balance updated.');setEdit(null);router.refresh();}}catch{toast.error("Could not save correction. Please retry.");}finally{saving.current=false;}});}}><h3>Edit {documentLabel(edit.document_number)}</h3><div className="tw-form">
 <label className="tw-f">Amount · {edit.currency}<input className="tw-in" required type="number" min="0.01" step="0.01" value={edit.amount} onChange={e=>setEdit({...edit,amount:Number(e.target.value)})}/></label>
 <label className="tw-f">Payment date<input className="tw-in" required type="date" value={edit.paid_at?.slice(0,10)??''} max={new Date().toISOString().slice(0,10)} onChange={e=>setEdit({...edit,paid_at:e.target.value})}/></label>
 <label className="tw-f">Method<select className="tw-in" value={edit.payment_method} onChange={e=>setEdit({...edit,payment_method:e.target.value})}>{['bank_transfer','wire','check','credit_card','debit_card','paypal','other'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label>
 <label className="tw-f">Reference<input className="tw-in" maxLength={120} value={edit.reference_number??''} onChange={e=>setEdit({...edit,reference_number:e.target.value})}/></label>
 <label className="tw-f">Notes<input className="tw-in" maxLength={2000} value={edit.notes??''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>
 <label className="tw-f">Correction reason<input className="tw-in" required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label></div><button className="tw-b pri" disabled={pending}>{pending?'Saving…':'Save correction'}</button> <button type="button" className="tw-b" disabled={pending} onClick={()=>setEdit(null)}>Cancel</button></form>}
 {deleting&&<form data-payment-delete className="tw-pad" onSubmit={e=>{e.preventDefault();if(saving.current||pending)return;saving.current=true;start(async()=>{try{const result=await deleteCollectionPayment({id:deleting.id,revision:deleting.revision,reason:deleteReason});if(!result.ok)toast.error(result.error);else{toast.success("Payment deleted. Invoice balance updated; audit retained.");setDeleting(null);router.refresh();}}catch{toast.error("Could not delete payment. Please retry.");}finally{saving.current=false;}});}}><h3>Delete {documentLabel(deleting.document_number)}?</h3><p className="tw-hint">This removes {deleting.currency} {money(deleting.amount)} from collected money and restores the invoice balance. The original receipt remains in the audit history. This does not send a refund.</p><label className="tw-f">Reason for deletion<input className="tw-in" required maxLength={500} value={deleteReason} onChange={e=>setDeleteReason(e.target.value)}/></label><button className="tw-b pri" disabled={pending||!deleteReason.trim()}>{pending?"Deleting…":"Confirm delete"}</button> <button className="tw-b" type="button" disabled={pending} onClick={()=>setDeleting(null)}>Cancel</button></form>}
 </div>;
}
