"use client";
import { formatDocumentNumberForDisplay as documentLabel } from "@/lib/documents/format-document-number";
import {useRef,useState,useTransition} from "react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { XIcon, TriangleAlertIcon, RotateCcwIcon, PencilIcon } from "lucide-react";
import {useRouter} from "next/navigation";
import {toast} from "sonner";
import {deleteCollectionPayment,restoreCollectionPayment,reviseCollectionPayment} from "../redesign-actions";
import {dateLabel,money,type CollectionPayment,type CollectionsPageData} from "../redesign-data";
export function CollectionPaymentHistory({payments,invoices}:{payments:CollectionPayment[];invoices:CollectionsPageData["invoices"]}) {
 const [search,setSearch]=useState("");const [edit,setEdit]=useState<CollectionPayment|null>(null);const [reason,setReason]=useState("");const [pending,start]=useTransition();const router=useRouter();
 const saving=useRef(false);const [deleting,setDeleting]=useState<CollectionPayment|null>(null);const [deleteReason,setDeleteReason]=useState("");
 const [restoring,setRestoring]=useState(false);
 const [deleteError,setDeleteError]=useState("");
 const rows=payments.filter(p=>`${p.document_number} ${documentLabel(p.document_number)} ${documentLabel(invoices.find(i=>i.id===p.invoice_id)?.document_number)} ${invoices.find(i=>i.id===p.invoice_id)?.document_number} ${invoices.find(i=>i.id===p.invoice_id)?.client_name} ${p.reference_number}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="tw-c"><div className="tw-ch"><span className="tw-ct">Payment history</span><span className="tw-cs">Latest 1,000 receipts · corrections retain an audit trail</span><span className="tw-sp"/><input className="tw-in" style={{width:240}} aria-label="Find recorded payment" placeholder="Client, invoice or reference" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="tw-sc"><table className="w-full text-left text-xs"><thead><tr>{['Date','Client','Invoice','Payment','Currency','Amount','Method','Reference','Notes',''].map((h,i)=><th key={i} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map(p=>{const inv=invoices.find(i=>i.id===p.invoice_id);return <tr key={p.id} className="border-t"><td className="p-3 whitespace-nowrap">{dateLabel(p.paid_at)}</td><td className="p-3">{inv?.client_name??'—'}</td><td className="p-3">{documentLabel(inv?.document_number)||'—'}</td><td className="p-3">{documentLabel(p.document_number)}</td><td className="p-3">{p.currency}</td><td className="p-3 tabular-nums">{money(p.amount)}</td><td className="p-3">{p.payment_method.replaceAll('_',' ')}</td><td className="p-3">{p.reference_number??'—'}</td><td className="p-3">{p.notes??'—'}</td><td className="p-3"><button type="button" className="inline-flex size-11 items-center justify-center rounded-full border text-blue-700 hover:bg-blue-50" aria-label={`Edit ${documentLabel(p.document_number)}`} title="Edit payment" onClick={()=>{setDeleting(null);setEdit({...p});setReason('');}} disabled={pending || p.status!=='completed'}><PencilIcon className="size-4" aria-hidden="true"/></button> {p.status==='completed'?<button type="button" className="inline-flex size-11 items-center justify-center rounded-full border border-red-200 text-red-700 hover:bg-red-50 focus-visible:outline-2 focus-visible:outline-red-600 disabled:opacity-50" title="Delete payment" aria-label={`Delete ${documentLabel(p.document_number)}`} disabled={pending} onClick={()=>{setRestoring(false);setEdit(null);setDeleting(p);setDeleteReason('');setDeleteError('');}}><span className="flex size-5 items-center justify-center rounded-full bg-red-100" aria-hidden="true"><XIcon className="size-3.5" /></span></button>:<span className="inline-flex flex-col gap-2"><span className="tw-hint">{p.status==='cancelled'?'Deleted · audit retained':p.status}</span>{p.can_restore&&<button type="button" className="inline-flex size-11 items-center justify-center rounded-full border text-blue-700 hover:bg-blue-50" aria-label={`Restore ${documentLabel(p.document_number)}`} title="Restore payment" disabled={pending} onClick={()=>{setRestoring(true);setEdit(null);setDeleting(p);setDeleteReason('');setDeleteError('');}}><RotateCcwIcon className="size-4" aria-hidden="true"/></button>}</span>}</td></tr>})}</tbody></table></div>{!rows.length&&<div className="tw-note">No recorded payments match. New receipts will appear here after recording.</div>}
 {edit&&<form data-payment-edit aria-busy={pending} className="tw-pad" onSubmit={e=>{e.preventDefault();if(saving.current || pending)return;saving.current=true;start(async()=>{try {const result=await reviseCollectionPayment({id:edit.id,revision:edit.revision,amount:edit.amount,date:edit.paid_at?.slice(0,10)??'',method:edit.payment_method,reference:edit.reference_number??'',notes:edit.notes??'',reason});if(!result.ok)toast.error(result.error);else{toast.success('Payment corrected. Invoice balance updated.');setEdit(null);router.refresh();}}catch{toast.error("Could not save correction. Please retry.");}finally{saving.current=false;}});}}><h3>Edit {documentLabel(edit.document_number)}</h3><div className="tw-form">
 <label className="tw-f">Amount · {edit.currency}<input className="tw-in" required type="number" min="0.01" step="0.01" value={edit.amount} onChange={e=>setEdit({...edit,amount:Number(e.target.value)})}/></label>
 <label className="tw-f">Payment date<input className="tw-in" required type="date" value={edit.paid_at?.slice(0,10)??''} max={new Date().toISOString().slice(0,10)} onChange={e=>setEdit({...edit,paid_at:e.target.value})}/></label>
 <label className="tw-f">Method<select className="tw-in" value={edit.payment_method} onChange={e=>setEdit({...edit,payment_method:e.target.value})}>{['bank_transfer','wire','check','credit_card','debit_card','paypal','other'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label>
 <label className="tw-f">Reference<input className="tw-in" maxLength={120} value={edit.reference_number??''} onChange={e=>setEdit({...edit,reference_number:e.target.value})}/></label>
 <label className="tw-f">Notes<input className="tw-in" maxLength={2000} value={edit.notes??''} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label>
 <label className="tw-f">Correction reason<input className="tw-in" required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label></div><button className="tw-b pri" disabled={pending}>{pending?'Saving…':'Save correction'}</button> <button type="button" className="tw-b" disabled={pending} onClick={()=>setEdit(null)}>Cancel</button></form>}
 <Dialog open={!!deleting} onOpenChange={open=>{if(!open&&!pending)setDeleting(null);}}><DialogContent showCloseButton={!pending} data-payment-delete onPointerDownOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(pending)e.preventDefault();}}>
 <DialogTitle className={`flex items-center gap-2 ${restoring?"text-blue-700":"text-red-700"}`}>{restoring?<RotateCcwIcon className="size-5" aria-hidden="true"/>:<TriangleAlertIcon className="size-5" aria-hidden="true"/>}{restoring?"Restore":"Delete"} {documentLabel(deleting?.document_number)}?</DialogTitle>
 <DialogDescription>{restoring?"This restores":"This removes"} {deleting?.currency} {money(deleting?.amount??0)} {restoring?"to collected money and reduces the invoice balance.":"from collected money and restores the invoice balance."} The original receipt and your note remain in the audit history. No refund is sent.</DialogDescription>
 {deleting&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();if(saving.current||pending||!deleteReason.trim())return;saving.current=true;setDeleteError("");start(async()=>{try{const result=await (restoring?restoreCollectionPayment:deleteCollectionPayment)({id:deleting.id,revision:deleting.revision,reason:deleteReason});if(!result.ok)setDeleteError(result.error ?? "Could not update the payment.");else{toast.success(`Payment ${restoring?"restored":"deleted"}. Invoice balance updated; audit retained.`);setDeleting(null);router.refresh();}}catch{setDeleteError("Could not update payment. Please retry.");}finally{saving.current=false;}});}}>
 <label className="block space-y-2"><span className="font-medium">{restoring?"Restoration":"Deletion"} note (required)</span><textarea className="min-h-24 w-full rounded-lg border p-3" required maxLength={500} disabled={pending} value={deleteReason} onChange={e=>setDeleteReason(e.target.value)} placeholder={restoring?"Explain why this payment should be restored":"Explain why this payment should be deleted"}/></label>
 {deleteError&&<p role="alert" className="text-sm text-red-700">{deleteError}</p>}
 <div className="flex justify-end gap-3"><button className="min-h-11 rounded-lg border px-4" type="button" disabled={pending} onClick={()=>setDeleting(null)}>Cancel</button><button className={`inline-flex min-h-11 items-center gap-2 rounded-lg px-4 font-medium text-white disabled:opacity-50 ${restoring?"bg-blue-600 hover:bg-blue-700":"bg-red-600 hover:bg-red-700"}`} disabled={pending||!deleteReason.trim()}>{restoring?<RotateCcwIcon className="size-4" aria-hidden="true"/>:<XIcon className="size-4" aria-hidden="true"/>}{pending?"Saving…":restoring?"Confirm restore":"Confirm delete"}</button></div></form>}
 </DialogContent></Dialog>
 </div>;
}
