"use client";
import {formatDocumentNumberForDisplay as documentLabel} from "@/lib/documents/format-document-number";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {toast} from "sonner";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
import {XIcon,TriangleAlertIcon,RotateCcwIcon,PencilIcon,CheckIcon,LinkIcon} from "lucide-react";
import {deleteCollectionPayment,restoreCollectionPayment,reviseCollectionPayment} from "../redesign-actions";
import {settleClientAdvance} from "../advance-actions";
import {dateLabel,money,type CollectionPayment,type CollectionsPageData} from "../redesign-data";
const icon="inline-flex size-11 shrink-0 items-center justify-center rounded-full border text-blue-700 hover:bg-blue-50 disabled:opacity-50";
export function CollectionPaymentHistory({payments,invoices,clients=[],campaigns=[]}:{payments:CollectionPayment[];invoices:CollectionsPageData["invoices"];clients?:CollectionsPageData["clients"];campaigns?:NonNullable<CollectionsPageData["campaigns"]>}){
 const router=useRouter();const [search,setSearch]=useState("");const [kind,setKind]=useState("all");const [edit,setEdit]=useState<CollectionPayment|null>(null);const [reason,setReason]=useState("");const [editError,setEditError]=useState("");const [pending,start]=useTransition();const saving=useRef(false);
 const [deleting,setDeleting]=useState<CollectionPayment|null>(null);const [deleteReason,setDeleteReason]=useState("");const [deleteError,setDeleteError]=useState("");const [restoring,setRestoring]=useState(false);
 const [settling,setSettling]=useState<CollectionPayment|null>(null);const [invoice,setInvoice]=useState("");const [settleAmount,setSettleAmount]=useState("");const [settleError,setSettleError]=useState("");
 const eligible=invoices.filter(i=>settling&&i.client_id===settling.client_id&&i.currency===settling.currency&&i.outstanding>0&&(!settling.advance_campaign_id||i.campaign_header_id===settling.advance_campaign_id));
 const rows=payments.filter(p=>{const i=invoices.find(i=>i.id===p.invoice_id);const name=clients.find(c=>c.id===p.client_id)?.name??i?.client_name;return(kind==="all"||(kind==="advance")===(p.invoice_id===null))&&[p.document_number,documentLabel(p.document_number),i?.document_number,documentLabel(i?.document_number),name,p.reference_number].join(" ").toLowerCase().includes(search.toLowerCase());}).sort((a,b)=>(b.paid_at??"").localeCompare(a.paid_at??"")||(b.created_at??"").localeCompare(a.created_at??"")||b.id.localeCompare(a.id));
 const formId="collection-inline-payment-edit";
 return <div className="tw-c"><div className="tw-ch"><span className="tw-ct">Payment history</span><span className="tw-cs">Newest payment date first · Actual is applied to an invoice; Advance is not yet applied</span><span className="tw-sp"/><select className="tw-in" style={{width:160}} aria-label="Payment classification" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All payments</option><option value="actual">Actual</option><option value="advance">Advance</option></select><input className="tw-in" style={{width:240}} aria-label="Find recorded payment" placeholder="Client, invoice or reference" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="tw-sc"><table className="w-full text-left text-xs" style={{minWidth:1700}}><colgroup>{[140,160,220,120,90,100,85,130,140,180,220,155].map((width,i)=><col key={i} style={{width}}/>)}</colgroup><thead><tr>{["Date ↓","Client","Campaign","Invoice","Type","Payment","Currency","Amount","Method","Reference","Notes","Actions"].map(h=><th key={h} className="p-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map(p=>{
 const inv=invoices.find(i=>i.id===p.invoice_id);const current=edit?.id===p.id?edit:null;
 return <tr key={p.id} className="border-t"><td className="p-3 whitespace-nowrap">{current?<input form={formId} aria-label="Payment date" className="tw-in" required type="date" max={new Date().toISOString().slice(0,10)} value={current.paid_at?.slice(0,10)??""} onChange={e=>setEdit({...current,paid_at:e.target.value})}/>:dateLabel(p.paid_at)}</td>
 <td className="p-3">{clients.find(c=>c.id===p.client_id)?.name??inv?.client_name??"—"}</td><td className="p-3">{campaigns.find(c=>c.id===(p.advance_campaign_id??inv?.campaign_header_id))?.name??inv?.campaign_name??"No campaign"}</td><td className="p-3">{documentLabel(inv?.document_number)||"Not issued / not linked"}</td><td className="p-3"><span className={p.invoice_id?"text-blue-700":"text-amber-700"}>{p.invoice_id?"Actual":"Advance"}</span></td><td className="p-3">{documentLabel(p.document_number)}</td><td className="p-3">{p.currency}</td>
 <td className="p-3 whitespace-nowrap tabular-nums">{current?<input form={formId} aria-label="Payment amount" className="tw-in" required type="number" min="0.01" step="0.01" max={inv?inv.outstanding+p.amount:undefined} value={current.amount} onChange={e=>setEdit({...current,amount:Number(e.target.value)})}/>:money(p.amount)}</td>
 <td className="p-3">{current?<select form={formId} aria-label="Payment method" className="tw-in" value={current.payment_method} onChange={e=>setEdit({...current,payment_method:e.target.value})}>{["bank_transfer","wire","check","credit_card","debit_card","paypal","other"].map(m=><option key={m} value={m}>{m.replaceAll("_"," ")}</option>)}</select>:p.payment_method.replaceAll("_"," ")}</td>
 <td className="p-3">{current?<input form={formId} aria-label="Payment reference" className="tw-in" maxLength={120} value={current.reference_number??""} onChange={e=>setEdit({...current,reference_number:e.target.value})}/>:p.reference_number??"—"}</td>
 <td className="p-3">{current?<div className="space-y-2"><input form={formId} aria-label="Payment notes" className="tw-in" maxLength={2000} value={current.notes??""} onChange={e=>setEdit({...current,notes:e.target.value})}/><input form={formId} aria-label="Correction reason" className="tw-in" placeholder="Correction reason (required)" required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/>{editError&&<span role="alert" className="text-red-700">{editError}</span>}</div>:p.notes??"—"}</td>
 <td className="p-3"><div className="flex gap-2">{current?<><button type="submit" form={formId} className={icon} title="Save changes (Ctrl+S)" aria-label="Save payment changes" disabled={pending}><CheckIcon className="size-4"/></button><button type="button" className={icon} title="Cancel editing" aria-label="Cancel editing" disabled={pending} onClick={()=>setEdit(null)}><XIcon className="size-4"/></button></>:p.status==="completed"?<><button type="button" className={icon} title="Edit payment" aria-label={"Edit "+documentLabel(p.document_number)} disabled={pending} onClick={e=>{e.preventDefault();setEdit({...p});setReason("");setEditError("");}}><PencilIcon className="size-4"/></button><button type="button" className="inline-flex size-11 shrink-0 items-center justify-center rounded-full border border-red-200 text-red-700 hover:bg-red-50" title="Delete payment" aria-label={"Delete "+documentLabel(p.document_number)} disabled={pending} onClick={()=>{setRestoring(false);setEdit(null);setDeleting(p);setDeleteReason("");setDeleteError("");}}><XIcon className="size-4"/></button>{!p.invoice_id&&<button className={icon} title="Settle advance against an invoice" aria-label={"Settle "+documentLabel(p.document_number)} disabled={pending} onClick={()=>{setEdit(null);setSettling(p);setInvoice("");setSettleAmount("");setSettleError("");}}><LinkIcon className="size-4"/></button>}</>:<span className="inline-flex items-center gap-2"><span className="tw-hint">{p.status==="cancelled"?"Deleted":p.status}</span>{p.can_restore&&<button className={icon} title="Restore payment" aria-label={"Restore "+documentLabel(p.document_number)} disabled={pending} onClick={()=>{setRestoring(true);setEdit(null);setDeleting(p);setDeleteReason("");setDeleteError("");}}><RotateCcwIcon className="size-4"/></button>}</span>}</div></td></tr>;
 })}</tbody></table></div>{!rows.length&&<div className="tw-note">No payments match these filters.</div>}
 {edit&&<form id={formId} data-payment-edit aria-busy={pending} onSubmit={e=>{e.preventDefault();if(saving.current||pending)return;saving.current=true;setEditError("");start(async()=>{try{const result=await reviseCollectionPayment({id:edit.id,revision:edit.revision,amount:edit.amount,date:edit.paid_at?.slice(0,10)??"",method:edit.payment_method,reference:edit.reference_number??"",notes:edit.notes??"",reason});if(!result.ok)setEditError(result.error??"Could not save changes.");else{toast.success("Payment updated.");setEdit(null);router.refresh();}}catch{setEditError("Could not save changes. Please retry.");}finally{saving.current=false;}});}}/>}
 <Dialog open={!!deleting} onOpenChange={open=>{if(!open&&!pending)setDeleting(null);}}><DialogContent showCloseButton={!pending} data-payment-delete onPointerDownOutside={e=>e.preventDefault()} onEscapeKeyDown={e=>{if(pending)e.preventDefault();}}>
 <DialogTitle className={`flex items-center gap-2 ${restoring?"text-blue-700":"text-red-700"}`}>{restoring?<RotateCcwIcon className="size-5" aria-hidden="true"/>:<TriangleAlertIcon className="size-5" aria-hidden="true"/>}{restoring?"Restore":"Delete"} {documentLabel(deleting?.document_number)}?</DialogTitle>
 <DialogDescription>{restoring?"This restores":"This removes"} {deleting?.currency} {money(deleting?.amount??0)} {restoring?"to collected money and reduces the invoice balance.":"from collected money and restores the invoice balance."} The original receipt and your note remain in the audit history. No refund is sent.</DialogDescription>
 {deleting&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();if(saving.current||pending||!deleteReason.trim())return;saving.current=true;setDeleteError("");start(async()=>{try{const result=await (restoring?restoreCollectionPayment:deleteCollectionPayment)({id:deleting.id,revision:deleting.revision,reason:deleteReason});if(!result.ok)setDeleteError(result.error ?? "Could not update the payment.");else{toast.success(`Payment ${restoring?"restored":"deleted"}. Invoice balance updated; audit retained.`);setDeleting(null);router.refresh();}}catch{setDeleteError("Could not update payment. Please retry.");}finally{saving.current=false;}});}}>
 <label className="block space-y-2"><span className="font-medium">{restoring?"Restoration":"Deletion"} note (required)</span><textarea className="min-h-24 w-full rounded-lg border p-3" required maxLength={500} disabled={pending} value={deleteReason} onChange={e=>setDeleteReason(e.target.value)} placeholder={restoring?"Explain why this payment should be restored":"Explain why this payment should be deleted"}/></label>
 {deleteError&&<p role="alert" className="text-sm text-red-700">{deleteError}</p>}
 <div className="flex justify-end gap-3"><button className="min-h-11 rounded-lg border px-4" type="button" disabled={pending} onClick={()=>setDeleting(null)}>Cancel</button><button className={`inline-flex min-h-11 items-center gap-2 rounded-lg px-4 font-medium text-white disabled:opacity-50 ${restoring?"bg-blue-600 hover:bg-blue-700":"bg-red-600 hover:bg-red-700"}`} disabled={pending||!deleteReason.trim()}>{restoring?<RotateCcwIcon className="size-4" aria-hidden="true"/>:<XIcon className="size-4" aria-hidden="true"/>}{pending?"Saving…":restoring?"Confirm restore":"Confirm delete"}</button></div></form>}
 </DialogContent></Dialog>
 <Dialog open={!!settling} onOpenChange={open=>{if(!open&&!pending)setSettling(null);}}><DialogContent data-payment-delete showCloseButton={!pending}><DialogTitle>Settle advance {documentLabel(settling?.document_number)}</DialogTitle><DialogDescription>Apply to an unsettled invoice for the same client and currency. This reclassifies existing cash as Actual; it does not record a second receipt. Any remainder stays Advance.</DialogDescription>
 <form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!settling||pending||saving.current)return;saving.current=true;start(async()=>{try{const result=await settleClientAdvance({id:settling.id,revision:settling.revision,invoice,amount:Number(settleAmount)});if(!result.ok)setSettleError(result.error??"Could not settle advance.");else{toast.success("Advance applied to invoice.");setSettling(null);router.refresh();}}catch{setSettleError("Could not settle advance. Reload and retry.");}finally{saving.current=false;}});}}><label className="block">Invoice<select className="block w-full rounded border p-2" required value={invoice} onChange={e=>{setInvoice(e.target.value);setSettleAmount(String(Math.min(settling?.amount??0,eligible.find(i=>i.id===e.target.value)?.outstanding??0)));}}><option value="">Select invoice</option>{eligible.map(i=><option key={i.id} value={i.id}>{documentLabel(i.document_number)} · {i.currency} {money(i.outstanding)} open</option>)}</select></label><label className="block">Amount to settle<input className="block w-full rounded border p-2" required type="number" step="0.01" min="0.01" max={Math.min(settling?.amount??0,eligible.find(i=>i.id===invoice)?.outstanding??0)} value={settleAmount} onChange={e=>setSettleAmount(e.target.value)}/></label>{!eligible.length&&<p>No eligible unsettled invoice for this client and currency.</p>}{settleError&&<p role="alert" className="text-red-700">{settleError}</p>}<div className="flex justify-end gap-3"><button type="button" className="rounded border p-2" disabled={pending} onClick={()=>setSettling(null)}>Cancel</button><button className="rounded bg-blue-600 p-2 text-white" disabled={pending||!invoice}>{pending?"Settling…":"Confirm settlement"}</button></div></form></DialogContent></Dialog>
 </div>;
}
