/**
 * Mock-seed / demo discovery profiles are permanently disabled in every runtime.
 * Unit tests may use in-memory fixtures only — never auto-insert mock_seed rows.
 *
 * Canonical copy for the Next.js app and scripts. Discovery-worker mirrors this in
 * `services/discovery-worker/src/discovery/demo-data.ts` (keep in sync).
 */
export function isDemoDataEnabled(
  _env: NodeJS.ProcessEnv = process.env
): boolean {
  return false;
}

/** Username pattern generated by the (now-removed) discovery-worker mock-seed fallback. */
export const MOCK_SEED_USERNAME_RE = /^tw_[a-z0-9]+_[a-z]{2}_[0-9]{2}$/i;

export function isMockSeedUsername(username: string | null | undefined): boolean {
  if (!username) return false;
  return MOCK_SEED_USERNAME_RE.test(username);
}

/**
 * Any username prefix that could only originate from synthetic/demo/mock/seed
 * generators. Real creator handles never start with these tokens. Used as a
 * bulletproof, environment-agnostic guard so synthetic profiles can never surface
 * — even if a legacy row somehow exists.
 */
export const SYNTHETIC_CREATOR_USERNAME_RE =
  /^(tw|demo|mock|seed|fake)_/i;

export function isSyntheticCreatorUsername(
  username: string | null | undefined
): boolean {
  if (!username) return false;
  return (
    SYNTHETIC_CREATOR_USERNAME_RE.test(username) || isMockSeedUsername(username)
  );
}

/** Drops any synthetic/demo/mock/seed creators from a result set (defensive). */
export function stripSyntheticCreators<T extends { username?: string | null }>(
  rows: readonly T[]
): T[] {
  return rows.filter((row) => !isSyntheticCreatorUsername(row.username));
}
