/** Major global brands — maintained separately from regional/MENA hints. */

export type CompanyHint = {
  categorySlug: string;
  subcategorySlug: string;
};

const auto = (subcategorySlug = "general_trading"): CompanyHint => ({
  categorySlug: "retail_ecommerce",
  subcategorySlug,
});

const tech = (subcategorySlug = "consumer_electronics"): CompanyHint => ({
  categorySlug: "retail_ecommerce",
  subcategorySlug,
});

const enterpriseTech = (): CompanyHint => ({
  categorySlug: "marketing_advertising_media_agencies",
  subcategorySlug: "technology_software",
});

const retail = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "retail_ecommerce",
  subcategorySlug,
});

const agency = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "marketing_advertising_media_agencies",
  subcategorySlug,
});

const beauty = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "beauty_personal_care",
  subcategorySlug,
});

const fashion = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "fashion_apparel",
  subcategorySlug,
});

const finance = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "financial_services_banking",
  subcategorySlug,
});

const telecom = (): CompanyHint => ({
  categorySlug: "telecommunications",
  subcategorySlug: "mobile_technology",
});

const healthcare = (): CompanyHint => ({
  categorySlug: "healthcare_wellness",
  subcategorySlug: "healthcare_products",
});

const transport = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "transportation_delivery",
  subcategorySlug,
});

const home = (): CompanyHint => ({
  categorySlug: "home_furniture",
  subcategorySlug: "home_furniture_interiors",
});

const food = (subcategorySlug: string): CompanyHint => ({
  categorySlug: "retail_ecommerce",
  subcategorySlug,
});

export const GLOBAL_COMPANY_HINTS: Record<string, CompanyHint> = {
  // Automotive & EV
  byd: auto(),
  "byd auto": auto(),
  "byd company": auto(),
  tesla: auto(),
  toyota: auto(),
  bmw: auto(),
  mercedes: auto(),
  "mercedes benz": auto(),
  "mercedes-benz": auto(),
  ford: auto(),
  gm: auto(),
  "general motors": auto(),
  hyundai: auto(),
  kia: auto(),
  nio: auto(),
  xpeng: auto(),
  "li auto": auto(),
  liauto: auto(),
  renault: auto(),
  stellantis: auto(),
  honda: auto(),
  nissan: auto(),
  audi: auto(),
  volkswagen: auto(),
  vw: auto(),
  porsche: auto(),
  ferrari: auto(),
  lamborghini: auto(),
  rivian: auto(),
  lucid: auto(),
  "lucid motors": auto(),
  geely: auto(),
  "great wall": auto(),
  "great wall motor": auto(),
  saic: auto(),
  chery: auto(),
  mahindra: auto(),
  "tata motors": auto(),
  subaru: auto(),
  mazda: auto(),
  mitsubishi: auto(),
  volvo: auto(),
  skoda: auto(),
  peugeot: auto(),
  citroen: auto(),
  fiat: auto(),
  jeep: auto(),
  dodge: auto(),
  chevrolet: auto(),
  cadillac: auto(),
  buick: auto(),
  gmc: auto(),
  infiniti: auto(),
  lexus: auto(),
  acura: auto(),
  genesis: auto(),
  polestar: auto(),
  vinfast: auto(),
  wuling: auto(),
  zeekr: auto(),
  avatr: auto(),
  hongqi: auto(),
  changan: auto(),
  dongfeng: auto(),
  faw: auto(),
  "faw group": auto(),

  // Technology & consumer electronics
  apple: tech(),
  microsoft: enterpriseTech(),
  google: enterpriseTech(),
  alphabet: enterpriseTech(),
  meta: agency("social_media_platform"),
  facebook: agency("social_media_platform"),
  instagram: agency("social_media_platform"),
  amazon: retail("online_marketplace"),
  samsung: tech(),
  huawei: tech(),
  xiaomi: tech(),
  dell: tech(),
  hp: tech(),
  "hewlett packard": tech(),
  ibm: enterpriseTech(),
  oracle: enterpriseTech(),
  sap: enterpriseTech(),
  intel: tech(),
  amd: tech(),
  nvidia: tech(),
  sony: tech(),
  lg: tech(),
  lenovo: tech(),
  asus: tech(),
  acer: tech(),
  toshiba: tech(),
  panasonic: tech(),
  canon: tech(),
  nikon: tech(),
  oppo: tech(),
  vivo: tech(),
  realme: tech(),
  oneplus: tech(),
  honor: tech(),
  tcl: tech(),
  hisense: tech(),
  sharp: tech(),
  philips: tech(),
  siemens: tech(),
  bosch: tech(),
  ge: tech(),
  "general electric": tech(),
  cisco: enterpriseTech(),
  salesforce: enterpriseTech(),
  adobe: enterpriseTech(),
  servicenow: enterpriseTech(),
  workday: enterpriseTech(),
  palantir: enterpriseTech(),
  spotify: agency("social_media_platform"),
  netflix: retail("entertainment_leisure_services"),
  twitter: agency("social_media_platform"),
  xcorp: agency("social_media_platform"),
  linkedin: agency("social_media_platform"),
  snap: agency("social_media_platform"),
  snapchat: agency("social_media_platform"),
  tiktok: agency("social_media_platform"),
  bytedance: agency("social_media_platform"),
  zoom: enterpriseTech(),
  slack: enterpriseTech(),
  shopify: retail("e_commerce"),
  stripe: finance("financial_services"),
  paypal: finance("financial_services"),
  square: finance("financial_services"),
  block: finance("financial_services"),

  // FMCG & food/beverage
  unilever: beauty("beauty_personal_care"),
  procter: beauty("beauty_personal_care"),
  "procter gamble": beauty("beauty_personal_care"),
  "procter & gamble": beauty("beauty_personal_care"),
  pg: beauty("beauty_personal_care"),
  "p&g": beauty("beauty_personal_care"),
  nestle: food("food_beverages"),
  nestlé: food("food_beverages"),
  "coca cola": food("food_beverages"),
  cocacola: food("food_beverages"),
  pepsi: food("food_beverages"),
  pepsico: food("food_beverages"),
  danone: food("food_beverages"),
  heinz: food("food_beverages"),
  kraft: food("food_beverages"),
  mondelez: food("food_snacks"),
  "johnson johnson": beauty("beauty_personal_care"),
  jnj: beauty("beauty_personal_care"),
  mars: food("food_snacks"),
  kellogg: food("food_snacks"),
  "general mills": food("food_beverages"),
  colgate: beauty("oral_care"),
  "colgate palmolive": beauty("oral_care"),
  reckitt: beauty("beauty_personal_care"),
  henkel: beauty("beauty_personal_care"),
  beiersdorf: beauty("skincare"),
  kimberly: beauty("beauty_personal_care"),
  "kimberly clark": beauty("beauty_personal_care"),
  scjohnson: beauty("beauty_personal_care"),
  "sc johnson": beauty("beauty_personal_care"),
  ferrero: food("food_snacks"),
  lindt: food("food_snacks"),
  "red bull": food("food_beverages"),
  redbull: food("food_beverages"),
  starbucks: food("food_restaurant"),
  mcdonalds: food("food_restaurant"),
  "mcdonald's": food("food_restaurant"),
  kfc: food("food_restaurant"),
  "burger king": food("food_restaurant"),
  subway: food("food_restaurant"),
  "pizza hut": food("food_restaurant"),
  dominos: food("food_restaurant"),
  "domino's": food("food_restaurant"),
  costa: food("food_restaurant"),
  "costa coffee": food("food_restaurant"),

  // Retail & e-commerce
  walmart: retail("retail_general_merchandise"),
  alibaba: retail("online_marketplace"),
  aliexpress: retail("online_marketplace"),
  taobao: retail("online_marketplace"),
  tmall: retail("online_marketplace"),
  jd: retail("online_marketplace"),
  "jd.com": retail("online_marketplace"),
  tesco: retail("retail_general_merchandise"),
  aldi: retail("retail_general_merchandise"),
  lidl: retail("retail_general_merchandise"),
  ikea: home(),
  costco: retail("retail_general_merchandise"),
  target: retail("retail_general_merchandise"),
  ebay: retail("online_marketplace"),
  etsy: retail("online_marketplace"),
  mercadolibre: retail("online_marketplace"),
  flipkart: retail("online_marketplace"),
  carrefour: retail("retail_general_merchandise"),
  bestbuy: retail("electronics_retail"),
  "best buy": retail("electronics_retail"),
  homedepot: retail("retail_general_merchandise"),
  "home depot": retail("retail_general_merchandise"),
  lowes: retail("retail_general_merchandise"),
  walgreens: retail("retail_general_merchandise"),
  cvs: retail("retail_general_merchandise"),
  boots: retail("retail_general_merchandise"),
  sephora: beauty("cosmetics"),
  shein: retail("online_fashion_retailer"),
  asos: retail("online_fashion_retailer"),
  zalando: retail("online_fashion_retailer"),
  wayfair: retail("online_furniture_marketplace"),
  lazada: retail("online_marketplace"),
  shopee: retail("online_marketplace"),
  coupang: retail("online_marketplace"),
  rakuten: retail("online_marketplace"),
  noon: retail("online_marketplace"),
  namshi: retail("online_fashion_retailer"),
  jumia: retail("online_marketplace"),

  // Marketing, advertising & media agencies
  omnicom: agency("advertising_agency"),
  wpp: agency("advertising_agency"),
  "wpp media": agency("advertising_agency"),
  publicis: agency("advertising_agency"),
  dentsu: agency("media_agency"),
  ipg: agency("advertising_agency"),
  havas: agency("advertising_agency"),
  accenture: agency("consulting_services"),
  deloitte: agency("consulting_services"),
  mindshare: agency("media_agency"),
  "mind share": agency("media_agency"),
  mediacom: agency("media_agency"),
  groupm: agency("media_investment_management"),
  "group m": agency("media_investment_management"),
  wavemaker: agency("media_agency"),
  essence: agency("media_agency"),
  hogarth: agency("media_production"),
  kantar: agency("consulting_services"),
  landor: agency("creative_agency"),
  mullenlowe: agency("advertising_agency"),
  "mullen lowe": agency("advertising_agency"),
  vmly: agency("creative_agency"),
  mccann: agency("advertising_agency"),
  bbdo: agency("advertising_agency"),
  ogilvy: agency("advertising_agency"),
  saatchi: agency("advertising_agency"),
  "saatchi saatchi": agency("advertising_agency"),
  grey: agency("advertising_agency"),
  tbwa: agency("advertising_agency"),
  jwt: agency("advertising_agency"),
  leo: agency("advertising_agency"),
  "leo burnett": agency("advertising_agency"),
  ddb: agency("advertising_agency"),
  fp7: agency("advertising_agency"),
  tpg: agency("media_agency"),
  carat: agency("media_agency"),

  // MENA media & advertising networks
  mcn: agency("media_agency"),
  "middle east communications network": agency("media_agency"),
  "middle east communications": agency("media_agency"),
  "ipg mediabrands": agency("advertising_agency"),
  mediabrands: agency("advertising_agency"),
  starcom: agency("media_agency"),
  zenith: agency("media_agency"),
  "um mena": agency("media_agency"),
  choueiri: agency("media_agency"),
  "choueiri group": agency("media_agency"),
  memac: agency("advertising_agency"),
  "memac ogilvy": agency("advertising_agency"),

  // Financial services & banking
  jpmorgan: finance("banking"),
  "jp morgan": finance("banking"),
  goldman: finance("investment_holding"),
  "goldman sachs": finance("investment_holding"),
  hsbc: finance("banking"),
  citi: finance("banking"),
  citibank: finance("banking"),
  citigroup: finance("banking"),
  blackrock: finance("investment_holding"),
  barclays: finance("banking"),
  chase: finance("banking"),
  "bank of america": finance("banking"),
  bofa: finance("banking"),
  wells: finance("banking"),
  "wells fargo": finance("banking"),
  morgan: finance("investment_holding"),
  "morgan stanley": finance("investment_holding"),
  ubs: finance("banking"),
  credit: finance("banking"),
  "credit suisse": finance("banking"),
  deutsche: finance("banking"),
  "deutsche bank": finance("banking"),
  bnp: finance("banking"),
  "bnp paribas": finance("banking"),
  santander: finance("banking"),
  ing: finance("banking"),
  lloyds: finance("banking"),
  rbc: finance("banking"),
  td: finance("banking"),
  scotiabank: finance("banking"),
  visa: finance("financial_services"),
  mastercard: finance("financial_services"),
  amex: finance("financial_services"),
  "american express": finance("financial_services"),
  berkshire: finance("investment_holding"),
  "berkshire hathaway": finance("investment_holding"),
  allianz: finance("financial_services"),
  axa: finance("financial_services"),
  prudential: finance("financial_services"),
  metlife: finance("financial_services"),
  aig: finance("financial_services"),

  // Telecommunications
  att: telecom(),
  "at&t": telecom(),
  verizon: telecom(),
  "deutsche telekom": telecom(),
  telekom: telecom(),
  "china mobile": telecom(),
  chinamobile: telecom(),
  "china unicom": telecom(),
  "china telecom": telecom(),
  telefonica: telecom(),
  orange: telecom(),
  vodafone: telecom(),
  stc: telecom(),
  etisalat: telecom(),
  du: telecom(),
  ooredoo: telecom(),
  zain: telecom(),
  "virgin mobile": telecom(),
  tmobile: telecom(),
  "t-mobile": telecom(),
  sprint: telecom(),
  bell: telecom(),
  rogers: telecom(),
  telus: telecom(),
  swisscom: telecom(),
  kpn: telecom(),
  bt: telecom(),
  "bt group": telecom(),
  nokia: telecom(),
  ericsson: telecom(),

  // Beauty & personal care
  loreal: beauty("cosmetics"),
  "l'oreal": beauty("cosmetics"),
  "estee lauder": beauty("cosmetics"),
  "estée lauder": beauty("cosmetics"),
  shiseido: beauty("cosmetics"),
  coty: beauty("cosmetics"),
  maybelline: beauty("cosmetics"),
  nivea: beauty("skincare"),
  olay: beauty("skincare"),
  dove: beauty("beauty_personal_care"),
  mac: beauty("cosmetics"),
  "mac cosmetics": beauty("cosmetics"),
  garnier: beauty("cosmetics"),
  clinique: beauty("cosmetics"),
  chanel: beauty("fragrances"),
  dior: beauty("fragrances"),
  lancome: beauty("cosmetics"),
  "lancôme": beauty("cosmetics"),
  avon: beauty("cosmetics"),
  revlon: beauty("cosmetics"),
  bath: beauty("beauty_personal_care"),
  "bath body works": beauty("beauty_personal_care"),
  ulta: beauty("cosmetics"),

  // Fashion & apparel
  nike: fashion("sportswear"),
  adidas: fashion("sportswear"),
  zara: fashion("fashion"),
  hm: fashion("fashion"),
  "h&m": fashion("fashion"),
  inditex: fashion("fashion"),
  lvmh: fashion("luxury_fashion"),
  kering: fashion("luxury_fashion"),
  gucci: fashion("luxury_fashion"),
  prada: fashion("luxury_fashion"),
  louisvuitton: fashion("luxury_fashion"),
  "louis vuitton": fashion("luxury_fashion"),
  puma: fashion("sportswear"),
  underarmour: fashion("sportswear"),
  "under armour": fashion("sportswear"),
  uniqlo: fashion("fashion"),
  mango: fashion("fashion"),
  hermes: fashion("luxury_fashion"),
  hermès: fashion("luxury_fashion"),
  burberry: fashion("luxury_fashion"),
  tiffany: fashion("luxury_fashion"),
  cartier: fashion("luxury_fashion"),
  rolex: fashion("luxury_fashion"),
  swatch: fashion("fashion"),
  levis: fashion("fashion"),
  "levi's": fashion("fashion"),
  gap: fashion("fashion"),
  newbalance: fashion("sportswear"),
  "new balance": fashion("sportswear"),
  lululemon: fashion("sportswear"),
  northface: fashion("sportswear"),
  "the north face": fashion("sportswear"),
  columbia: fashion("sportswear"),
  patagonia: fashion("sustainable_fashion"),
  ralph: fashion("fashion"),
  "ralph lauren": fashion("fashion"),
  tommy: fashion("fashion"),
  "tommy hilfiger": fashion("fashion"),
  calvin: fashion("fashion"),
  "calvin klein": fashion("fashion"),

  // Healthcare & wellness
  pfizer: healthcare(),
  novartis: healthcare(),
  roche: healthcare(),
  gsk: healthcare(),
  astrazeneca: healthcare(),
  merck: healthcare(),
  sanofi: healthcare(),
  bayer: healthcare(),
  abbvie: healthcare(),
  bristol: healthcare(),
  "bristol myers": healthcare(),
  "bristol-myers squibb": healthcare(),
  eli: healthcare(),
  "eli lilly": healthcare(),
  amgen: healthcare(),
  gilead: healthcare(),
  biogen: healthcare(),
  moderna: healthcare(),
  regeneron: healthcare(),
  takeda: healthcare(),
  biontech: healthcare(),

  // Transportation & delivery
  uber: transport("ride_hailing_app"),
  lyft: transport("ride_hailing_app"),
  didi: transport("ride_hailing_app"),
  grab: transport("ride_hailing_app"),
  careem: transport("ride_hailing_app"),
  bolt: transport("ride_hailing_app"),
  fedex: transport("delivery_services"),
  dhl: transport("delivery_services"),
  ups: transport("delivery_services"),
  usps: transport("delivery_services"),
  emirates: transport("transportation_app"),
  etihad: transport("transportation_app"),
  qatarairways: transport("transportation_app"),
  "qatar airways": transport("transportation_app"),
  lufthansa: transport("transportation_app"),
  airfrance: transport("transportation_app"),
  "air france": transport("transportation_app"),
  british: transport("transportation_app"),
  "british airways": transport("transportation_app"),
  delta: transport("transportation_app"),
  united: transport("transportation_app"),
  "united airlines": transport("transportation_app"),
  american: transport("transportation_app"),
  "american airlines": transport("transportation_app"),
  southwest: transport("transportation_app"),
  singapore: transport("transportation_app"),
  "singapore airlines": transport("transportation_app"),
  talabat: transport("delivery_services"),
  deliveroo: transport("delivery_services"),

  // Home & furniture
  homecentre: home(),
  "home centre": home(),
  potterbarn: home(),
  "pottery barn": home(),
  williams: home(),
  "williams sonoma": home(),
  crate: home(),
  "crate barrel": home(),
  "crate & barrel": home(),
  ashley: home(),
  "ashley furniture": home(),

  // Government, sports & nonprofit
  fifa: {
    categorySlug: "government_sports_nonprofit",
    subcategorySlug: "sports_federations_leagues",
  },
  uefa: {
    categorySlug: "government_sports_nonprofit",
    subcategorySlug: "sports_federations_leagues",
  },
  olympic: {
    categorySlug: "government_sports_nonprofit",
    subcategorySlug: "national_olympic_sports_committees",
  },
};
