"use client";
import {useState,useTransition} from 'react';import {useRouter,useSearchParams} from 'next/navigation';import Link from 'next/link';import {toast} from 'sonner';import {vatMonths,roundVat,type VatLedger} from '../ledger-model';import {recordVatPayment} from '../ledger-actions';
const amount=(n:number)=>n.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export function VatLedgerWorkspace({data}:{data:VatLedger}){
 const params=useSearchParams();const periods=vatMonths(data);const latest=periods[0]?.period??new Date().toISOString().slice(0,7);const initial=params.get('period')??latest;
 const [year,setYear]=useState(initial.slice(0,4));const [month,setMonth]=useState(initial.slice(5,7));const [currency,setCurrency]=useState(params.get('currency')??periods[0]?.currency??'EGP');const [country,setCountry]=useState(params.get('country')??periods[0]?.country??'EG');const [pay,setPay]=useState(false);const [request,setRequest]=useState('');const [pending,start]=useTransition();const router=useRouter();
 const selected=periods.filter(r=>r.period.startsWith(year)&&(!month||r.period.endsWith('-'+month))&&r.currency===currency&&r.country===country);const sum=(key:'vatIn'|'vatOut'|'paid'|'payable'|'credit')=>selected.reduce((s,r)=>s+r[key],0);
 const matches=(d:string)=>d.startsWith(year)&&(!month||d.slice(5,7)===month);
 const entries=[...data.entries.filter(e=>matches(e.date)&&e.currency===currency&&e.country===country).map(e=>({...e,paid:0})),...data.payments.filter(p=>matches(p.period)&&p.currency===currency&&p.country_code===country).map(p=>({id:p.id,date:p.paid_at,name:p.authority,invoice:p.reference,country:p.country_code,currency:p.currency,vatIn:0,vatOut:0,paid:p.amount,source:`Tax payment · ${p.period.slice(0,7)}`}))].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));let running=0;const lines=entries.map(e=>({...e,balance:running=roundVat(running+e.vatIn-e.vatOut-e.paid)}));
 const paymentRows=data.payments.filter(p=>matches(p.period)&&p.currency===currency&&p.country_code===country);
 function exportCsv(){const rows=[['Date','Client / supplier','Invoice / reference','Source','Currency','VAT in (output)','VAT out (input)','Tax paid','Balance'],...lines.map(e=>[e.date,e.name,e.invoice,e.source,e.currency,e.vatIn,e.vatOut,e.paid,e.balance])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`vat-${year}-${month||'all'}-${currency}.csv`;a.click();URL.revokeObjectURL(a.href);}
 return <div className="space-y-4 text-sm"><div className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4">
 <label>Year<select className="block rounded border p-2" aria-label="VAT year" value={year} onChange={e=>setYear(e.target.value)}>{[...new Set([...Array.from({length:10},(_,i)=>(new Date().getFullYear()-i).toString()),...periods.map(p=>p.period.slice(0,4))])].sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label>
 <label>Month<select className="block rounded border p-2" aria-label="VAT month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">All months</option>{months.map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select></label>
 <label>Currency<select className="block rounded border p-2" value={currency} onChange={e=>setCurrency(e.target.value)}>{[...new Set(['EGP','AED','USD',...periods.map(p=>p.currency)])].map(c=><option key={c}>{c}</option>)}</select></label>
 <label>Tax country<select className="block rounded border p-2" value={country} onChange={e=>setCountry(e.target.value)}>{[...new Set(['EG','AE','SA',...periods.map(p=>p.country)])].map(c=><option key={c}>{c}</option>)}</select></label>
 <button className="rounded border px-3 py-2" onClick={exportCsv}>Export statement</button><button className="rounded bg-blue-600 px-3 py-2 text-white" disabled={!month||country==='Unspecified'} onClick={()=>{setPay(true);setRequest(crypto.randomUUID());}}>Record VAT payment</button><Link className="text-blue-600" href="/billing/creator-invoices">Creator invoices</Link></div>
 <p className="text-muted-foreground">VAT in = output VAT on issued client invoices. VAT out = input VAT on confirmed creator invoices. Amounts are separated by country and currency. Tax payments are assigned to the selected tax month; their actual payment dates are retained.</p>
 <div className="grid gap-3 sm:grid-cols-5">{[['VAT in',sum('vatIn')],['VAT out',sum('vatOut')],['Tax paid',sum('paid')],['Remaining payable',sum('payable')],['Credit / excess paid',sum('credit')]].map(([k,v])=><div key={String(k)} className="rounded-xl border bg-white p-4"><div>{k}</div><strong className="block text-lg tabular-nums">{currency} {amount(Number(v))}</strong></div>)}</div>
 {!!sum('payable')&&<div role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-3">{currency} {amount(sum('payable'))} needs to be paid for the selected months. This is the recorded balance, not a filing deadline.</div>}
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{['Date','Client / creator / authority','Invoice / reference','Source','VAT in','VAT out','Tax paid','Balance'].map(h=><th key={h} className="p-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{lines.map(e=><tr key={e.id} className="border-t">{[e.date,e.name,e.invoice,e.source,amount(e.vatIn),amount(e.vatOut),amount(e.paid),amount(e.balance)].map((v,i)=><td key={i} className="p-3 tabular-nums">{v}</td>)}</tr>)}</tbody></table>{!lines.length&&<p className="p-4">No confirmed VAT entries or payments in this period.</p>}</div>
 <details className="rounded-xl border bg-white p-4"><summary>Tax payment details ({paymentRows.length})</summary>{paymentRows.map(p=><div key={p.id} className="border-t py-3">{p.paid_at} · {p.authority} · {currency} {amount(p.amount)} · {p.method.replaceAll('_',' ')} · {p.reference}<p>{p.notes||'No notes'}</p></div>)}</details>
 {data.provisional.length>0&&<div className="rounded-xl border bg-white p-4"><strong>Campaign cost estimates — excluded from confirmed VAT</strong><p>{data.provisional.map(p=>`${p.currency} ${amount(p.amount)}`).join(' · ')}</p><p>These costs have no supplier invoice tax dates. Add and confirm creator invoices under Billing to include their VAT in the correct month. Do not add these estimates to the statement.</p></div>}
 {pay&&<form className="rounded-xl border bg-white p-4" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);fd.set('request_id',request);fd.set('period',`${year}-${month}-01`);fd.set('currency',currency);fd.set('country_code',country);start(async()=>{const result=await recordVatPayment(fd);if(!result.ok)toast.error(result.error);else{toast.success('VAT payment recorded.');setPay(false);router.refresh();}});}}><h3 className="font-semibold">Record payment already made · {year}-{month} · {country} · {currency}</h3><div className="my-3 grid gap-3 sm:grid-cols-3">{[['amount','Amount','number'],['paid_at','Payment date','date'],['authority','Tax authority','text'],['reference','Bank / receipt reference','text'],['notes','Notes','text']].map(([name,label,type])=><label key={name}>{label}<input className="block w-full rounded border p-2" name={name} type={type} required={name!=='notes'} step={type==='number'?'0.01':undefined} min={type==='number'?'0.01':undefined} max={type==='date'?new Date().toISOString().slice(0,10):undefined}/></label>)}<label>Method<select className="block w-full rounded border p-2" name="method">{['bank_transfer','wire','check','cash','other'].map(m=><option key={m}>{m}</option>)}</select></label></div><button className="rounded bg-blue-600 px-4 py-2 text-white" disabled={pending}>{pending?'Saving…':'Save payment record'}</button> <button type="button" className="rounded border px-4 py-2" onClick={()=>setPay(false)}>Cancel</button></form>}
 </div>;
}
