"use client";
import {useState,useTransition} from 'react';import {useRouter,useSearchParams} from 'next/navigation';import Link from 'next/link';import {toast} from 'sonner';import {vatMonths,roundVat,type VatLedger} from '../ledger-model';import {recordVatPayment} from '../ledger-actions';
const amount=(n:number)=>n.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export function VatLedgerWorkspace({data}:{data:VatLedger}){
 const params=useSearchParams();const periods=vatMonths(data);const initial=params.get('period')??'';
 const [year,setYear]=useState(initial.slice(0,4));const [month,setMonth]=useState(initial.slice(5,7));const [currency,setCurrency]=useState(params.get('currency')??'');const [country,setCountry]=useState(params.get('country')??'');const [pay,setPay]=useState(false);const [request,setRequest]=useState('');const [pending,start]=useTransition();const router=useRouter();
 const selected=periods.filter(r=>r.period.startsWith(year)&&(!month||r.period.endsWith('-'+month))&&(!currency||r.currency===currency)&&(!country||r.country===country));
 const matches=(d:string)=>(!year||d.startsWith(year))&&(!month||d.slice(5,7)===month);
 const entries=[...data.entries.filter(e=>matches(e.date)&&(!currency||e.currency===currency)&&(!country||e.country===country)).map(e=>({...e,paid:0})),...data.payments.filter(p=>matches(p.period)&&(!currency||p.currency===currency)&&(!country||p.country_code===country)).map(p=>({id:p.id,date:p.paid_at,name:p.authority,invoice:p.reference,country:p.country_code,currency:p.currency,vatIn:0,vatOut:0,paid:p.amount,source:`Tax payment · ${p.period.slice(0,7)}`,included:true,status:'Recorded'}))].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const running=new Map<string,number>();const lines=entries.map(e=>{const key=e.country+'|'+e.currency;const balance=roundVat((running.get(key)??0)+(e.included===false?0:e.vatIn-e.vatOut-e.paid));running.set(key,balance);return {...e,balance};});
 const groups=[...new Set(selected.map(r=>r.country+'|'+r.currency))].map(key=>{const rows=selected.filter(r=>r.country+'|'+r.currency===key);return {key,country:rows[0].country,currency:rows[0].currency,vatIn:rows.reduce((s,r)=>s+r.vatIn,0),vatOut:rows.reduce((s,r)=>s+r.vatOut,0),paid:rows.reduce((s,r)=>s+r.paid,0),payable:rows.reduce((s,r)=>s+r.payable,0),credit:rows.reduce((s,r)=>s+r.credit,0)};});
 const paymentRows=data.payments.filter(p=>matches(p.period)&&(!currency||p.currency===currency)&&(!country||p.country_code===country));
 function exportCsv(){const rows=[['Date','Client / supplier','Invoice / reference','Source','Status','Included in balance','Country','Currency','VAT in (output)','VAT out (input)','Tax paid','Balance'],...lines.map(e=>[e.date,e.name,e.invoice,e.source,e.status??'',e.included===false?'No':'Yes',e.country,e.currency,e.vatIn,e.vatOut,e.paid,e.balance])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`vat-${year}-${month||'all'}-${currency}.csv`;a.click();URL.revokeObjectURL(a.href);}
 return <div><section className="tw-c"><div className="tw-ch"><span className="tw-ct">VAT statement</span><span className="tw-cs">{lines.length} of {data.entries.length+data.payments.length} records · all invoices visible by default</span></div><div className="tw-form">
 <label className="fl-field">Year<select disabled={pay} className="fl-input" aria-label="VAT year" value={year} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{[...new Set([...Array.from({length:10},(_,i)=>(new Date().getFullYear()-i).toString()),...periods.map(p=>p.period.slice(0,4))])].sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label>
 <label className="fl-field">Month<select disabled={pay} className="fl-input" aria-label="VAT month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">All months</option>{months.map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select></label>
 <label className="fl-field">Currency<select disabled={pay} className="fl-input" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="">All currencies</option>{[...new Set(['EGP','AED','USD',...data.entries.map(p=>p.currency),...periods.map(p=>p.currency)])].map(c=><option key={c}>{c}</option>)}</select></label>
 <label className="fl-field">Tax country<select disabled={pay} className="fl-input" value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{[...new Set(['EG','AE','SA',...data.entries.map(p=>p.country),...periods.map(p=>p.country)])].map(c=><option key={c}>{c}</option>)}</select></label>
 </div><div className="fl-tools"><button className="tw-b" onClick={exportCsv}>Export statement</button><button className="tw-b pri" disabled={!year||!month||!currency||!country||country==='Unspecified'} onClick={()=>{setPay(true);setRequest(crypto.randomUUID());}}>Record VAT payment</button><Link className="tw-b" href="/billing/creator-invoices">Creator invoices</Link></div>
 <p className="tw-note">Issued invoices follow the Billing register rules. Cancelled, superseded and unconfirmed creator invoices remain visible but are excluded from payable balances. VAT in = output VAT on issued client invoices. VAT out = input VAT on confirmed creator invoices. Amounts are separated by country and currency. Tax payments are assigned to the selected tax month; their actual payment dates are retained. Choose a year, month, currency and country to record a tax payment.</p></section>
 {groups.map(g=><section className="tw-c" key={g.key}><div className="tw-ch"><span className="tw-ct">{g.country} · {g.currency}</span><span className="tw-cs">Confirmed VAT · {year||'All years'} · {month?months[Number(month)-1]:'All months'}</span><span className="tw-sp"/><span className={g.payable>0?'fl-status warning':'fl-status'}>{g.payable>0?'Needs to be paid':'No payment due'}</span></div><div className="fl-metrics">{[['VAT in',g.vatIn],['VAT out',g.vatOut],['Tax paid',g.paid],['Remaining payable',g.payable],['Credit / excess paid',g.credit]].map(([k,v])=><div className="fl-metric" key={String(k)}><small>{k}</small><strong>{amount(Number(v))}</strong></div>)}</div></section>)}
 <section className="tw-c"><div className="tw-ch"><span className="tw-ct">Invoice and payment details</span><span className="tw-cs">Balances run separately by country and currency</span></div><div className="tw-sc"><table className="fl-table"><thead><tr>{['Date','Client / creator / authority','Invoice / reference','Source / status','Country · CCY','VAT in','VAT out','Tax paid','Balance'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{lines.map(e=><tr key={e.id} className={e.included===false?'fl-excluded':''}><td>{e.date||'Not set'}</td><td>{e.name}</td><td>{e.invoice||'Not provided'}</td><td>{e.source}<br/><span className={e.included===false?'fl-status warning':'fl-status'}>{e.status||'Included'}</span>{e.included===false&&<small className="block">Excluded from balance</small>}</td><td>{e.country} · {e.currency}</td>{[e.vatIn,e.vatOut,e.paid,e.balance].map((v,i)=><td className="fl-number" key={i}>{amount(v)}</td>)}</tr>)}</tbody></table></div>{!lines.length&&<p className="tw-note">No invoices or payments match these filters.</p>}</section>
 <details className="tw-c tw-pad"><summary>Tax payment details ({paymentRows.length})</summary>{paymentRows.map(p=><div key={p.id} className="border-t py-3">{p.paid_at} · {p.authority} · {p.country_code} · {p.currency} {amount(p.amount)} · {p.method.replaceAll('_',' ')} · {p.reference}<p>{p.notes||'No notes'}</p></div>)}</details>
 {data.provisional.length>0&&<div className="tw-c tw-pad"><strong>Campaign cost estimates — excluded from confirmed VAT</strong><p>{data.provisional.map(p=>`${p.currency} ${amount(p.amount)}`).join(' · ')}</p><p>These costs have no supplier invoice tax dates. Add and confirm creator invoices under Billing to include their VAT in the correct month. Do not add these estimates to the statement.</p></div>}
 {pay&&<form className="tw-c tw-pad" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);fd.set('request_id',request);fd.set('period',`${year}-${month}-01`);fd.set('currency',currency);fd.set('country_code',country);start(async()=>{const result=await recordVatPayment(fd);if(!result.ok)toast.error(result.error);else{toast.success('VAT payment recorded.');setPay(false);router.refresh();}});}}><h3 className="font-semibold">Record payment already made · {year}-{month} · {country} · {currency}</h3><div className="tw-form">{[['amount','Amount','number'],['paid_at','Payment date','date'],['authority','Tax authority','text'],['reference','Bank / receipt reference','text'],['notes','Notes','text']].map(([name,label,type])=><label key={name} className="fl-field">{label}<input className="fl-input" name={name} type={type} required={name!=='notes'} step={type==='number'?'0.01':undefined} min={type==='number'?'0.01':undefined} max={type==='date'?new Date().toISOString().slice(0,10):undefined}/></label>)}<label className="fl-field">Method<select disabled={pay} className="fl-input" name="method">{['bank_transfer','wire','check','cash','other'].map(m=><option key={m}>{m}</option>)}</select></label></div><button className="tw-b pri" disabled={pending}>{pending?'Saving…':'Save payment record'}</button> <button type="button" className="tw-b" onClick={()=>setPay(false)}>Cancel</button></form>}
 </div>;
}
