/**
 * Creator Search Requirements (CSR) — Phase 1 contract.
 *
 * CSR is the structured statement of "what creators this campaign needs",
 * generated by Studio from the Campaign Strategy Document plus already-extracted
 * Campaign Intelligence. It is NOT a second intelligence extractor: it reads
 * validated intelligence, it never re-parses a brief.
 *
 * Two layers, because Discovery's filter surface is a closed allowlist
 * (DISCOVERY_SEARCH_FILTER_KEYS) and deliberately excludes campaign intent
 * (CIP_FIELDS_EXCLUDED_FROM_DISCOVERY):
 *
 *   Layer 1 `search`    — projectable onto DiscoveryMappedFilter[] for retrieval.
 *   Layer 2 `strategic` — campaign intent. Never a SQL filter; consumed by Studio
 *                         scoring / mix selection in later phases.
 *
 * Phase 1 is foundation + shadow evaluation only: nothing here participates in
 * live creator search, ranking, or slate membership.
 */

import type { DiscoveryPlatform } from "@/lib/discovery/types";
import type { InfluencerTier } from "@/lib/creators/influencer-tier";
import type { DiscoverySearchFilterKey } from "@/features/campaign-intelligence-profile/services/discovery-search-mapping/types";
import type {
  BrandSafetyLevel,
  FieldProvenance,
  NormalizedGender,
} from "@/features/campaign-intelligence-profile/services/normalization/types";

export const CREATOR_SEARCH_REQUIREMENTS_SCHEMA_VERSION = 1 as const;

/**
 * Requirement strength. `mandatory` / `preferred` mirror the existing
 * ConstraintTier in the Enterprise Constraint Engine so CSR tiers can be handed
 * to it directly in a later phase; `exploratory` is the widening band.
 */
export type RequirementTier = "mandatory" | "preferred" | "exploratory";

/**
 * Where a requirement value came from, in precedence order.
 * `brief_regex_fallback` marks values derived by deriveCreatorCategoriesFromBrief
 * — kept working in Phase 1, but explicitly labelled as the weakest source.
 */
export type RequirementSource =
  | "operator"
  | "strategy"
  | "validated_intel"
  | "facts"
  | "brief_regex_fallback";

/** One requirement value plus the provenance needed to explain it later. */
export type CreatorRequirement<V = string> = {
  /** Stable within a CSR build: `${group}:${normalizedValue}`. */
  id: string;
  value: V;
  tier: RequirementTier;
  /** 0-100 relative importance inside its group. */
  weight: number;
  source: RequirementSource;
  /** Why the campaign asked for this — surfaced verbatim in evidence later. */
  rationale: string;
  confidence: number;
  /** Present only when this requirement is expressible as a Discovery filter. */
  discoveryKey?: DiscoverySearchFilterKey;
};

/** Negative constraints. No Discovery allowlist key exists for these today. */
export type CreatorExclusions = {
  creatorIds: string[];
  handles: string[];
  categories: string[];
  keywords: string[];
  competitorBrands: string[];
};

/** Layer 1 — projectable onto the Discovery filter allowlist. */
export type CreatorSearchLayer = {
  platforms: CreatorRequirement<DiscoveryPlatform>[];
  creatorCountries: CreatorRequirement[];
  audienceCountries: CreatorRequirement[];
  cities: CreatorRequirement[];
  languages: CreatorRequirement[];
  primaryCategories: CreatorRequirement[];
  secondaryCategories: CreatorRequirement[];
  niches: CreatorRequirement[];
  contentTopics: CreatorRequirement[];
  audienceGender?: CreatorRequirement<NormalizedGender>;
  audienceAgeMin?: CreatorRequirement<number>;
  audienceAgeMax?: CreatorRequirement<number>;
  /**
   * Wide guardrails spanning the WHOLE tier mix — deliberately not a per-tier
   * window. Tier allocation is a portfolio decision and lives in Layer 2.
   */
  followerFloor?: CreatorRequirement<number>;
  followerCeiling?: CreatorRequirement<number>;
  engagementFloor?: CreatorRequirement<number>;
  brandSafety: BrandSafetyLevel;
  exclusions: CreatorExclusions;
};

/** Layer 2 — campaign intent. Never projected onto Discovery filters. */
export type CreatorStrategicLayer = {
  objective: string;
  objectiveKind: "awareness" | "acquisition" | "both" | "other";
  kpis: Array<{ metric: string; target: string; why: string }>;
  /** From strategy.creatorTierStrategy — allocation, not a search filter. */
  tierMix: Array<{ tier: InfluencerTier; percent: number; why: string }>;
  archetypes: CreatorRequirement[];
  contentFormats: CreatorRequirement[];
  audienceInterests: CreatorRequirement[];
  /** From strategy.pillars. */
  contentPillars: Array<{ title: string; what: string; why: string }>;
  coverage: {
    targetCreatorCount: number | null;
    minCategoriesCovered: number;
    minPlatformsCovered: number;
  };
  budget?: { amount: number; currency: string };
};

/** A requirement the campaign needs but could not be resolved. Never invented. */
export type CreatorRequirementGap = {
  field: string;
  reason: string;
  /** True when the gap would make a Strategy-driven search unsound. */
  blocking: boolean;
};

/** Reference to the Strategy revision this CSR was generated from. */
export type CreatorSearchRequirementsStrategyRef = {
  id: string;
  version: number;
  createdAt: string;
};

export type CreatorSearchRequirements = {
  schemaVersion: typeof CREATOR_SEARCH_REQUIREMENTS_SCHEMA_VERSION;
  /** Absent when no Strategy document was available at build time. */
  strategyRef?: CreatorSearchRequirementsStrategyRef;
  campaignIntelligenceProfileId?: string;
  generatedAt: string;
  search: CreatorSearchLayer;
  strategic: CreatorStrategicLayer;
  /** Per-field provenance, mirroring ValidatedCampaignIntelligence.fieldEvidence. */
  fieldEvidence: Record<string, FieldProvenance>;
  gaps: CreatorRequirementGap[];
};
