/**
 * Field paths merged from creator_dna_staging → creator_dna on identity promote.
 * Kept separate so promoteStaging does not import the completeness engine cycle.
 */

export const DNA_STAGING_PROMOTE_FIELD_PATHS = [
  "identity.displayName",
  "identity.bio",
  "identity.avatarUrl",
  "identity.handle",
  "identity.platform",
  "identity.isVerified",
  "platforms.primaryPlatform",
  "platforms.accountCount",
  "platforms.crossPlatformReach",
  "audience.country",
  "audience.countries",
  "audience.cities",
  "audience.languages",
  "audience.interests",
  "audience.categories",
  "audience.hashtags",
  "audience.mentions",
  "audience.audienceGender",
  "audience.audienceAgeBands",
  "audience.audienceCities",
  "audience.languagePrimary",
  "metrics.followers",
  "metrics.following",
  "metrics.postsCount",
  "metrics.engagementRate",
  "metrics.avgLikes",
  "metrics.avgComments",
  "metrics.avgViews",
  "scores.aiCategory",
  "scores.aiNiche",
  "scores.authenticityScore",
  "brandSafety.engagementQuality",
  "brandSafety.fakeFollowers",
  "brandSafety.verificationLevel",
  "commercial.estimatedRate",
  "commercial.typicalDeliverables",
  "commercial.campaignFrequency",
  "commercial.responseSpeed",
  "commercial.historicalBrandCategories",
  "historicalPerformance.campaignsCompleted",
  "historicalPerformance.avgCampaignRoi",
  "historicalPerformance.repeatBrandRate",
  "historicalPerformance.onTimeDeliveryRate",
  "historicalPerformance.avgEngagementTrend",
  "contact.email",
  "contact.phone",
  "contact.links",
  "content.profileUrl",
  "content.username",
  "content.recentPublications",
] as const;
