import {
  ClockIcon,
  DownloadIcon,
  EyeIcon,
  GitCompareIcon,
  HistoryIcon,
  RefreshCwIcon,
  Share2Icon,
  SparklesIcon,
} from "lucide-react";

import { cn } from "@/lib/utils";

import type { OutputView } from "../output-registry";
import { OutputStatusBadge } from "./output-status-badge";
import { formatEstimatedTime, formatOrigin, formatRelativeTime, formatSize } from "./output-format";

export type OutputCardActions = {
  onOpen?: (kind: OutputView["kind"]) => void;
  onPreview?: (kind: OutputView["kind"]) => void;
  onRegenerate?: (kind: OutputView["kind"]) => void;
  onExport?: (kind: OutputView["kind"]) => void;
  onShare?: (kind: OutputView["kind"]) => void;
  onCompare?: (kind: OutputView["kind"]) => void;
  onHistory?: (kind: OutputView["kind"]) => void;
};

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-2">
      <span className="text-[11px] text-muted-foreground">{label}</span>
      <span className="truncate text-[11px] font-medium text-foreground/90">{value}</span>
    </div>
  );
}

function ActionButton({
  label,
  icon: Icon,
  onClick,
  disabled,
  primary,
}: {
  label: string;
  icon: typeof EyeIcon;
  onClick?: () => void;
  disabled?: boolean;
  primary?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled || !onClick}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[11px] font-semibold transition-colors disabled:cursor-not-allowed disabled:opacity-40",
        primary
          ? "bg-[#1D9E75] text-white hover:bg-[#178a66]"
          : "border border-border text-foreground/80 hover:bg-muted/60"
      )}
    >
      <Icon className="size-3.5" />
      {label}
    </button>
  );
}

/**
 * A rich Campaign Output card for the Outputs Center — the asset-library tile.
 * Shows name, description, status (with precise stale reason), version, and the
 * full metadata block, plus the output's actions.
 */
export function OutputCard({ output, actions }: { output: OutputView; actions?: OutputCardActions }) {
  const isGenerated = output.status !== "not_generated";
  const hasHistory = output.version > 1;

  return (
    <div className="flex flex-col gap-3 rounded-xl border border-border bg-background p-4 shadow-sm transition-shadow hover:shadow-md">
      <div className="flex items-start justify-between gap-2">
        <div className="min-w-0">
          <h3 className="truncate text-sm font-bold text-foreground">{output.label}</h3>
          <p className="mt-0.5 line-clamp-2 text-[11px] leading-snug text-muted-foreground">
            {output.description}
          </p>
        </div>
        {!output.generatable ? (
          <span className="shrink-0 rounded-full border border-border bg-muted/40 px-2 py-0.5 text-[9px] font-medium text-muted-foreground">
            Soon
          </span>
        ) : null}
      </div>

      <div className="flex items-center justify-between gap-2">
        <OutputStatusBadge status={output.status} staleReason={output.staleReason} />
        {isGenerated ? (
          <span className="text-[11px] font-semibold text-muted-foreground">v{output.version}</span>
        ) : null}
      </div>

      {output.status === "needs_update" && output.staleReason ? (
        <p className="rounded-md border border-amber-500/30 bg-amber-500/5 px-2.5 py-1.5 text-[11px] text-amber-700 dark:text-amber-300">
          Reason: {output.staleReason}
        </p>
      ) : null}

      <div className="space-y-1 border-y border-border/60 py-2.5">
        <MetaRow label="Last updated" value={formatRelativeTime(output.updatedAt)} />
        <MetaRow label="Generator" value={output.generatorVersion ? `v${output.generatorVersion}` : "—"} />
        <MetaRow label="Generated by" value={isGenerated ? formatOrigin(output.origin) : "—"} />
        <MetaRow label="Est. time" value={formatEstimatedTime(output.estimatedGenerationMs)} />
        {isGenerated ? <MetaRow label="Size" value={formatSize(output.sizeBytes)} /> : null}
      </div>

      <div>
        <p className="mb-1 flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
          <SparklesIcon className="size-3" /> Source data
        </p>
        <div className="flex flex-wrap gap-1">
          {output.sourceData.map((source) => (
            <span
              key={source}
              className="rounded-full border border-border/70 px-1.5 py-0.5 text-[10px] text-muted-foreground"
            >
              {source}
            </span>
          ))}
        </div>
      </div>

      <div className="mt-auto flex flex-wrap gap-1.5 pt-1">
        {isGenerated ? (
          <>
            <ActionButton label="Open" icon={EyeIcon} onClick={actions?.onOpen && (() => actions.onOpen!(output.kind))} primary />
            <ActionButton label="Preview" icon={EyeIcon} onClick={actions?.onPreview && (() => actions.onPreview!(output.kind))} />
            <ActionButton
              label={output.status === "needs_update" ? "Regenerate" : "Regenerate"}
              icon={RefreshCwIcon}
              onClick={actions?.onRegenerate && (() => actions.onRegenerate!(output.kind))}
              disabled={!output.generatable}
            />
            <ActionButton label="Export" icon={DownloadIcon} onClick={actions?.onExport && (() => actions.onExport!(output.kind))} />
            <ActionButton label="Share" icon={Share2Icon} onClick={actions?.onShare && (() => actions.onShare!(output.kind))} />
            <ActionButton
              label="Compare"
              icon={GitCompareIcon}
              onClick={actions?.onCompare && (() => actions.onCompare!(output.kind))}
              disabled={!hasHistory}
            />
            <ActionButton
              label="History"
              icon={HistoryIcon}
              onClick={actions?.onHistory && (() => actions.onHistory!(output.kind))}
              disabled={!hasHistory}
            />
          </>
        ) : (
          <ActionButton
            label="Generate"
            icon={ClockIcon}
            onClick={actions?.onRegenerate && (() => actions.onRegenerate!(output.kind))}
            disabled={!output.generatable}
            primary
          />
        )}
      </div>
    </div>
  );
}
